// ignore_for_file: lines_longer_than_80_chars
part of 'toxicity_analyzer_controller.dart';

// ═══════════════════════════════════════════════════════════════════════════
// THE GOOD — 100 positive / healthy relationship pattern metrics
// IDs: good_1 … good_100   severityWeight: 1
// ═══════════════════════════════════════════════════════════════════════════

List<PsychologicalMetric> _buildPackGoodCatalog() {
  const defs = [
    (name: 'Active Listening Cues', description: 'Detects paraphrasing, clarifying questions, and demonstrated understanding of the partner\'s perspective in text.'),
    (name: 'Appreciation Expression', description: 'Identifies specific gratitude, recognition of effort, and acknowledgment of partner\'s positive qualities or actions.'),
    (name: 'Affirmation Language', description: 'Looks for statements that validate the partner\'s feelings, experiences, worth, or right to have needs.'),
    (name: 'Collaborative Tone', description: 'Measures use of "we," joint problem-solving language, and framing issues as shared challenges to address together.'),
    (name: 'Curiosity About Partner', description: 'Tracks asking questions about the partner\'s thoughts, feelings, day, preferences, or inner experience.'),
    (name: 'Vulnerability Expression', description: 'Identifies sharing fears, insecurities, needs, or emotional truths without defensiveness or blame.'),
    (name: 'Humor as Connection', description: 'Detects playful shared laughter that brings partners together rather than mocking or belittling.'),
    (name: 'Reassurance Offering', description: 'Looks for proactive statements that provide comfort, security, or confidence to the anxious partner.'),
    (name: 'Compliment Frequency', description: 'Measures genuine specific praise about appearance, character, abilities, or positive actions.'),
    (name: 'Emotional Availability', description: 'Assesses responsiveness to the partner\'s emotional needs, presence during distress, and willingness to engage.'),
    (name: 'Gratitude Habit', description: 'Identifies regular expressions of thanks for small things, effort, presence, or support.'),
    (name: 'Supportive Language', description: 'Tracks statements offering help, encouragement, belief in the partner\'s abilities, or standing beside them.'),
    (name: 'Gentle Disagreement', description: 'Measures ability to express different views while preserving respect, curiosity, and the relationship.'),
    (name: 'Apology Sincerity', description: 'Detects genuine remorse, understanding of impact, and commitment to change without excuses.'),
    (name: 'Forgiveness Acceptance', description: 'Looks for willingness to let go of past harm, move forward, and rebuild trust after repair.'),
    (name: 'Quality Time Initiation', description: 'Identifies offers to spend focused time together, plan activities, or create connection moments.'),
    (name: 'Physical Affection Cues', description: 'Tracks mentions of touch, hugs, kisses, or physical closeness as expressions of care and intimacy.'),
    (name: 'Shared Joy Recognition', description: 'Measures celebrating partner\'s wins, achievements, happiness, or good news with genuine enthusiasm.'),
    (name: 'Conflict Resolution Effort', description: 'Identifies attempts to find solutions, compromise, or restore peace after disagreement.'),
    (name: 'Patience Demonstration', description: 'Detects tolerance for partner\'s pace, struggles, learning curve, or emotional processing needs.'),
    (name: 'Perspective-Taking Language', description: 'Looks for statements showing understanding of the partner\'s viewpoint, context, or emotional reality.'),
    (name: 'Reliability Signals', description: 'Tracks following through on promises, showing up consistently, and being dependable.'),
    (name: 'Respect for Differences', description: 'Measures acceptance of partner\'s unique traits, preferences, opinions, and ways of being.'),
    (name: 'Openness to Feedback', description: 'Identifies receptiveness to partner\'s concerns, willingness to hear criticism, and desire to improve.'),
    (name: 'Validation of Emotions', description: 'Detects acknowledgment that the partner\'s feelings are real, understandable, and worthy of attention.'),
    (name: 'Encouragement Language', description: 'Looks for statements that inspire confidence, motivate action, or support the partner\'s goals.'),
    (name: 'Intimate Disclosure', description: 'Identifies sharing personal thoughts, dreams, fears, or secrets that deepen emotional connection.'),
    (name: 'Attunement Signals', description: 'Measures noticing the partner\'s mood, needs, or distress without being told explicitly.'),
    (name: 'Positive Reframing', description: 'Detects finding silver linings, growth opportunities, or constructive angles in difficult situations.'),
    (name: 'Commitment Language', description: 'Tracks expressions of dedication, long-term thinking, and investment in the relationship\'s future.'),
    (name: 'Flexibility Demonstration', description: 'Identifies willingness to adapt plans, adjust expectations, or meet the partner halfway.'),
    (name: 'Protective Language', description: 'Looks for statements showing the partner\'s safety, wellbeing, and interests matter deeply.'),
    (name: 'Celebration of Milestones', description: 'Measures acknowledging anniversaries, achievements, or meaningful moments together.'),
    (name: 'Constructive Feedback', description: 'Detects offering suggestions for improvement that are kind, specific, and growth-focused.'),
    (name: 'Presence During Hardship', description: 'Identifies staying engaged when the partner is struggling, grieving, or facing challenges.'),
    (name: 'Admiration Expression', description: 'Tracks genuine respect for the partner\'s character, strength, intelligence, or resilience.'),
    (name: 'Playfulness Indicators', description: 'Looks for lighthearted teasing, inside jokes, or fun interactions that strengthen bonding.'),
    (name: 'Empathic Mirroring', description: 'Measures reflecting back the partner\'s emotions to show understanding and validation.'),
    (name: 'Acceptance Language', description: 'Detects embracing the partner as they are, including flaws, without demanding change.'),
    (name: 'Supportive Presence', description: 'Identifies being there without fixing, offering comfort through listening and companionship.'),
    (name: 'Genuine Interest', description: 'Tracks asking follow-up questions and remembering details about the partner\'s life and concerns.'),
    (name: 'Reciprocal Effort', description: 'Measures both partners contributing equally to emotional work, planning, and relationship maintenance.'),
    (name: 'Forgiveness Language', description: 'Looks for releasing grudges, offering second chances, and choosing to move past hurt.'),
    (name: 'Mutual Respect Signals', description: 'Detects treating the partner as an equal, honoring their opinions, and valuing their input.'),
    (name: 'Emotional Honesty', description: 'Identifies truthful expression of feelings without manipulation, exaggeration, or strategic withholding.'),
    (name: 'Supportive Listening', description: 'Measures allowing the partner to fully express without interrupting, judging, or immediately problem-solving.'),
    (name: 'Affectionate Nicknames', description: 'Tracks use of loving terms of endearment that convey warmth and intimate connection.'),
    (name: 'Shared Laughter', description: 'Identifies moments of mutual humor and joy that create positive bonding experiences.'),
    (name: 'Thoughtful Gestures', description: 'Looks for small acts of kindness, remembering preferences, or doing things to make partner happy.'),
    (name: 'Confidence in Partner', description: 'Detects belief in the partner\'s abilities, potential, and capacity to handle challenges.'),
    (name: 'Healthy Interdependence', description: 'Measures balance between togetherness and independence, supporting each other\'s autonomy.'),
    (name: 'Conflict De-escalation', description: 'Identifies soft language, breaks, or solution-offering to calm heated discussions.'),
    (name: 'Genuine Apology', description: 'Tracks full acknowledgment of wrongdoing without minimizing, defending, or shifting blame.'),
    (name: 'Emotional Support Offers', description: 'Looks for proactive check-ins, asking how the partner is doing, and offering help.'),
    (name: 'Respectful Boundaries', description: 'Measures honoring the partner\'s stated limits while maintaining own healthy boundaries.'),
    (name: 'Positive Anticipation', description: 'Detects excitement about the future together, planning ahead, and looking forward to shared experiences.'),
    (name: 'Attentiveness Signals', description: 'Identifies remembering important dates, preferences, and details that show the partner matters.'),
    (name: 'Encouraging Growth', description: 'Tracks supporting the partner\'s personal development, learning, and pursuit of goals.'),
    (name: 'Tender Language', description: 'Looks for soft, caring word choices that convey gentleness and emotional warmth.'),
    (name: 'Mutual Accountability', description: 'Measures both partners taking responsibility for their actions and their impact.'),
    (name: 'Celebration of Partner', description: 'Detects publicly or privately expressing pride, joy, or admiration for the partner.'),
    (name: 'Consistent Affection', description: 'Identifies regular expressions of love that do not fluctuate based on performance or compliance.'),
    (name: 'Emotional Attunement', description: 'Tracks sensing and responding to subtle shifts in the partner\'s emotional state.'),
    (name: 'Collaborative Decision-Making', description: 'Measures discussing options together and making choices that consider both partners\' needs.'),
    (name: 'Reassurance Without Demand', description: 'Looks for offering comfort and security without requiring the partner to earn it.'),
    (name: 'Authentic Connection', description: 'Detects genuine presence, real sharing, and dropping pretense in interactions.'),
    (name: 'Mutual Encouragement', description: 'Identifies both partners cheering each other on and celebrating efforts not just outcomes.'),
    (name: 'Respectful Questioning', description: 'Tracks asking about the partner\'s perspective with genuine curiosity rather than interrogation.'),
    (name: 'Loving Consistency', description: 'Measures showing up the same way in good times and hard times, reliable in affection.'),
    (name: 'Emotional Reciprocity', description: 'Looks for both partners sharing feelings, needs, and vulnerabilities in balanced ways.'),
    (name: 'Joyful Presence', description: 'Detects genuine happiness in the partner\'s company and enthusiasm for time together.'),
    (name: 'Constructive Dialogue', description: 'Identifies conversations that move toward understanding rather than winning or proving right.'),
    (name: 'Protective Advocacy', description: 'Tracks standing up for the partner, defending them, and prioritizing their wellbeing.'),
    (name: 'Mindful Communication', description: 'Measures thoughtful word choice, considering impact before speaking, and intentional messaging.'),
    (name: 'Relationship Investment', description: 'Looks for time, energy, and resources devoted to nurturing the partnership.'),
    (name: 'Secure Base Language', description: 'Detects offering stability, safety, and a foundation from which the partner can explore.'),
    (name: 'Mutual Admiration', description: 'Identifies both partners expressing respect and appreciation for each other\'s qualities.'),
    (name: 'Tender Moments', description: 'Tracks creating or recognizing intimate quiet moments of connection and closeness.'),
    (name: 'Genuine Curiosity', description: 'Looks for authentic interest in understanding the partner\'s thoughts, feelings, and experiences.'),
    (name: 'Loving Acceptance', description: 'Detects embracing the partner\'s whole self, including imperfections and past.'),
    (name: 'Mutual Growth Support', description: 'Identifies both partners encouraging each other\'s development and celebrating progress.'),
    (name: 'Warm Tone Indicators', description: 'Tracks use of affectionate language, kind phrasing, and gentle communication style.'),
    (name: 'Responsive Engagement', description: 'Measures quick, engaged responses to the partner\'s messages and emotional bids.'),
    (name: 'Shared Values Alignment', description: 'Looks for references to common beliefs, goals, or life philosophies that unite the couple.'),
    (name: 'Unconditional Support', description: 'Detects standing by the partner through difficulties without making support conditional.'),
    (name: 'Intimate Vulnerability', description: 'Identifies sharing deep fears, dreams, or insecurities that deepen emotional bonds.'),
    (name: 'Mutual Respect Language', description: 'Tracks honoring each other\'s perspectives, choices, and autonomy in communication.'),
    (name: 'Positive Framing', description: 'Measures seeing the best in situations and the partner, focusing on strengths.'),
    (name: 'Collaborative Problem Solving', description: 'Looks for working together toward solutions that benefit both partners equally.'),
    (name: 'Emotional Validation', description: 'Detects confirming that the partner\'s feelings make sense and are acceptable.'),
    (name: 'Consistent Kindness', description: 'Identifies regular small acts of care that show the partner is thought of and valued.'),
    (name: 'Mutual Celebration', description: 'Tracks both partners genuinely happy about each other\'s successes and joys.'),
    (name: 'Secure Attachment Language', description: 'Measures expressing trust, comfort with intimacy, and confidence in the relationship.'),
    (name: 'Thoughtful Consideration', description: 'Looks for making decisions with the partner\'s needs and feelings in mind.'),
    (name: 'Loving Presence', description: 'Detects being fully present and engaged, showing the partner they matter most.'),
    (name: 'Genuine Care Language', description: 'Tracks authentic expressions of concern, care, and investment in the partner\'s wellbeing.'),
    (name: 'Relationship Commitment', description: 'Measures expressing dedication to the partnership and willingness to work through challenges.'),
    (name: 'Authentic Love Expression', description: 'Looks for genuine consistent expressions of love that feel real and unconditional.'),
  ];
  return List<PsychologicalMetric>.generate(
    defs.length,
    (i) => PsychologicalMetric(
      id: 'good_${i + 1}',
      name: defs[i].name,
      description: defs[i].description,
      severityWeight: 1,
    ),
    growable: false,
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// THE BAD — 100 warning-sign / mid-severity harmful pattern metrics
// IDs: bad_1 … bad_100   severityWeight: 3
// ═══════════════════════════════════════════════════════════════════════════

List<PsychologicalMetric> _buildPackBadCatalog() {
  const defs = [
    (name: 'Passive Aggression', description: 'Detects indirect hostility through procrastination, forgetfulness, sarcasm, or subtle sabotage instead of direct expression.'),
    (name: 'Guilt Weaponization', description: 'Identifies using guilt, shame, or obligation language to manipulate decisions or prevent boundary-setting.'),
    (name: 'Emotional Blackmail', description: 'Flags threats of self-harm, abandonment, or withdrawal of love to control behavior or prevent discussion.'),
    (name: 'Chronic Complaining', description: 'Tracks persistent negativity, rumination, or complaint without seeking solutions or collaborative change.'),
    (name: 'Comparison Shaming', description: 'Identifies unfavorable comparisons to exes, friends, or family to shame or coerce behavior change.'),
    (name: 'Conditional Listening', description: 'Detects listening only when it benefits the listener or serves their agenda rather than genuine understanding.'),
    (name: 'Selective Memory', description: 'Tracks convenient forgetting of promises, agreements, or past harmful behavior to avoid accountability.'),
    (name: 'Attention Seeking Through Crisis', description: 'Identifies dramatic escalation, crisis creation, or exaggeration to gain focus or sympathy.'),
    (name: 'Boundary Testing', description: 'Detects repeated probing or pushing of stated limits to determine if they will be enforced.'),
    (name: 'Withholding Information', description: 'Identifies deliberate omission of relevant facts, context, or transparency to maintain control.'),
    (name: 'Disproportionate Anger', description: 'Tracks anger responses that are significantly larger than the triggering incident warrants.'),
    (name: 'Reassurance Addiction', description: 'Flags constant need for validation, repeated questions about commitment, or endless proof of love.'),
    (name: 'Conversation Avoidance', description: 'Detects refusal to engage with concerns, avoidance phrases, or shutting down important discussions.'),
    (name: 'Contradiction Pattern', description: 'Identifies contradictory statements, promises, or positions that create confusion or destabilization.'),
    (name: 'Dismissal Through Labeling', description: 'Flags labeling concerns as "crazy," "dramatic," "paranoid," or "overreacting" to invalidate them.'),
    (name: 'Selective Empathy', description: 'Detects empathy offered only when convenient or when it serves the speaker\'s interests.'),
    (name: 'Transactional Framing', description: 'Identifies "you owe me," "after all I\'ve done," or viewing relationship acts as creating debt.'),
    (name: 'Grievance Recycling', description: 'Tracks bringing up old grievances repeatedly or using past harm as ammunition in current conflicts.'),
    (name: 'Demand Language', description: 'Flags imperatives, commands, or ultimatums rather than requests or collaborative problem-solving.'),
    (name: 'Emotional Unavailability', description: 'Detects consistent refusal to engage emotionally, share feelings, or provide comfort.'),
    (name: 'Hostile Interpretation', description: 'Identifies taking neutral statements as attacks or interpreting ambiguous messages as hostile.'),
    (name: 'Entitlement Framing', description: 'Flags language suggesting the speaker deserves special treatment, exceptions, or priority.'),
    (name: 'Criticism Disguised as Help', description: 'Detects criticism wrapped in "I\'m just trying to help" or "for your own good" language.'),
    (name: 'Neglect Patterns', description: 'Identifies consistent failure to meet emotional, physical, or relational needs.'),
    (name: 'Conflict Rumination', description: 'Tracks obsessive rehashing of conflicts without moving toward resolution or closure.'),
    (name: 'Sensitivity Dismissal', description: 'Flags statements like "you\'re too sensitive" or "you\'re overreacting" to dismiss feelings.'),
    (name: 'Competitive Framing', description: 'Detects framing relationship as a competition where one partner must win or dominate.'),
    (name: 'Double Standards', description: 'Identifies applying different rules to self versus partner or changing expectations arbitrarily.'),
    (name: 'Affection as Punishment', description: 'Flags removing affection, attention, or communication as retaliation for perceived wrongs.'),
    (name: 'Blame Rotation', description: 'Tracks rotating blame between partner, circumstances, and external factors to avoid accountability.'),
    (name: 'Rhetorical Mockery', description: 'Detects rhetorical or sarcastic questions used to mock rather than understand.'),
    (name: 'Sacrifice Reminders', description: 'Identifies reminding partner of sacrifices, favors, or support to create debt and compliance.'),
    (name: 'Deliberate Escalation', description: 'Flags deliberately escalating intensity to overwhelm partner\'s ability to respond rationally.'),
    (name: 'Strategic Vulnerability', description: 'Detects sharing emotions only when it serves manipulation or control purposes.'),
    (name: 'Deflection Through Counterattack', description: 'Identifies turning focus away from partner\'s concerns by raising unrelated issues or countercharges.'),
    (name: 'Superiority Language', description: 'Flags superiority language, condescension, or framing partner as beneath them.'),
    (name: 'Conflict Exit Pattern', description: 'Detects pattern of leaving conversations, refusing to engage, or creating distance during conflict.'),
    (name: 'Negative Bias', description: 'Tracks consistently interpreting neutral or positive actions as negative or suspicious.'),
    (name: 'Agency Denial', description: 'Identifies "I have to," "you make me," or language removing personal agency from the speaker.'),
    (name: 'Silence as Control', description: 'Flags using silence or non-response as a form of punishment or control.'),
    (name: 'Privacy Hypocrisy', description: 'Detects refusing to share information while demanding transparency from the partner.'),
    (name: 'Unsolicited Harsh Feedback', description: 'Identifies harsh feedback presented as "constructive" or "helpful" without consent.'),
    (name: 'Conditional Care', description: 'Flags support offered only when partner complies with speaker\'s expectations.'),
    (name: 'Impact Denial', description: 'Detects "I didn\'t mean it that way" or "you\'re reading too much into it" after causing harm.'),
    (name: 'Debt Mentality', description: 'Tracks bringing up past help or support to create debt and control current behavior.'),
    (name: 'Responsibility Evasion', description: 'Flags consistent pattern of not taking responsibility for the impact of actions.'),
    (name: 'Needs Dismissal', description: 'Identifies treating partner\'s needs as inconvenient, unreasonable, or unimportant.'),
    (name: 'Emotional Manipulation', description: 'Flags using emotions strategically to control outcomes or prevent accountability.'),
    (name: 'Intimacy Avoidance', description: 'Tracks consistent withdrawal from emotional or physical closeness without explanation.'),
    (name: 'Veiled Criticism', description: 'Identifies criticism disguised as jokes, observations, or casual comments.'),
    (name: 'Concern Minimization', description: 'Flags reducing partner\'s concerns to insignificance or exaggeration.'),
    (name: 'Guilt Enforcement', description: 'Identifies using guilt or shame to ensure partner complies with expectations.'),
    (name: 'Apology Resistance', description: 'Tracks resistance to apologizing, explaining away harm, or refusing to acknowledge impact.'),
    (name: 'Perspective Rejection', description: 'Flags refusing to consider or validate partner\'s viewpoint or experience.'),
    (name: 'Emotional Rationing', description: 'Detects deliberately limiting emotional expression or connection as a form of control.'),
    (name: 'Obligation Manipulation', description: 'Flags using past support or sacrifice to manipulate current decisions.'),
    (name: 'Resistance to Growth', description: 'Tracks resistance to modifying harmful behavior despite requests or demonstrated impact.'),
    (name: 'Harm Denial', description: 'Detects refusing to acknowledge or take seriously the impact of one\'s own behavior.'),
    (name: 'Loaded Questions', description: 'Flags critical intent disguised as innocent questions or expressions of curiosity.'),
    (name: 'Contemptuous Tone', description: 'Identifies dismissive attitude or disdain conveyed through text patterns and word choice.'),
    (name: 'Guilt Trip Cycling', description: 'Detects repeatedly using guilt about past support or sacrifice to control current behavior.'),
    (name: 'Emotional Guardedness', description: 'Tracks refusing to share emotions, fears, or needs with partner as protective withholding.'),
    (name: 'Boundary Negotiation', description: 'Flags treating stated limits as suggestions or negotiable rather than firm commitments.'),
    (name: 'Emotional Absence', description: 'Detects consistent refusal to provide emotional support or engaged presence.'),
    (name: 'Favor Tracking', description: 'Flags keeping mental score of favors, support, or sacrifices for later leverage.'),
    (name: 'Honesty Avoidance', description: 'Detects pattern of withholding truth, omitting facts, or being deliberately vague.'),
    (name: 'Validity Denial', description: 'Identifies treating partner\'s feelings, needs, or concerns as invalid or illegitimate.'),
    (name: 'Advice Disguised Criticism', description: 'Flags criticism presented as concern, advice, or a helpful observation.'),
    (name: 'Superiority Indicators', description: 'Detects superiority, mockery, or disdain in language or communication style.'),
    (name: 'Repair Resistance', description: 'Tracks resistance to making amends, reconnecting, or rebuilding after conflict.'),
    (name: 'Effort Dismissal', description: 'Flags minimizing or ignoring partner\'s attempts to improve or address issues.'),
    (name: 'Emotional Distance Pattern', description: 'Detects long-term pattern of emotional distance or refusal to engage authentically.'),
    (name: 'Inferiority Framing', description: 'Identifies framing partner as inferior, flawed, or unworthy of full respect.'),
    (name: 'Feedback Resistance', description: 'Detects resistance to hearing criticism, refusing to listen, or shutting down discussion.'),
    (name: 'Worry Dismissal', description: 'Identifies treating partner\'s worries or fears as unfounded or irrational.'),
    (name: 'Fault Finding', description: 'Flags chronic pattern of finding fault, complaining about, or attacking partner\'s character.'),
    (name: 'Sacrifice Guilt Cycling', description: 'Identifies repeatedly bringing up past support to create guilt or control behavior.'),
    (name: 'Commitment Ambiguity', description: 'Tracks unclear or wavering commitment language, mixed signals, or reluctance to commit.'),
    (name: 'Request Dismissal', description: 'Flags ignoring, refusing, or delaying response to partner\'s reasonable requests.'),
    (name: 'Emotional Control Tactics', description: 'Detects strategic use of emotions to control outcomes or prevent accountability.'),
    (name: 'Exchange Mentality', description: 'Flags viewing relationship through lens of debt, obligation, or transactional exchange.'),
    (name: 'Personal Development Resistance', description: 'Detects resistance to personal development, learning, or changing harmful patterns.'),
    (name: 'Improvement Rejection', description: 'Identifies minimizing or rejecting partner\'s efforts to improve or address issues.'),
    (name: 'Chronic Criticism', description: 'Flags chronic pattern of criticism wrapped in concern, helpfulness, or care language.'),
    (name: 'Solution Avoidance', description: 'Detects consistent pattern of avoiding closure, moving forward, or finding workable solutions.'),
    (name: 'Blame Deflection Pattern', description: 'Flags habitual pattern of redirecting responsibility to external factors or the partner.'),
    (name: 'Dismissive Responses', description: 'Identifies pattern of dismissing partner\'s input, ideas, or suggestions without consideration.'),
    (name: 'Resentment Expression', description: 'Detects tone of resentment, bitterness, or long-held frustration in communication.'),
    (name: 'Ambivalent Messaging', description: 'Flags mixed messages about commitment, unclear desire to continue, or push-pull dynamics.'),
    (name: 'Expectation Shifting', description: 'Identifies changing expectations without communication, then blaming partner for not meeting them.'),
    (name: 'Deflection Habit', description: 'Detects habitual avoidance of direct answers or redirection of conversations away from accountability.'),
    (name: 'Manipulation Through Kindness', description: 'Flags exaggerated generosity used strategically to create obligation or lower defenses.'),
    (name: 'Chronic Lateness Pattern', description: 'Identifies consistent disregard for partner\'s time through lateness or broken scheduling commitments.'),
    (name: 'Progress Minimization', description: 'Tracks dismissing or failing to acknowledge the partner\'s genuine personal growth or improvements.'),
    (name: 'Emotional Weaponizing', description: 'Detects using partner\'s disclosed vulnerabilities or fears against them in conflict.'),
    (name: 'Gaslighting-Adjacent Tactics', description: 'Identifies subtle reality-distorting tactics that create self-doubt without full gaslighting.'),
    (name: 'Passive Stonewalling', description: 'Flags subtle disengagement, monosyllabic responses, or checked-out presence as avoidance.'),
    (name: 'Narrative Control', description: 'Detects insisting on being the sole authority on what happened, how it felt, or what was meant.'),
  ];
  return List<PsychologicalMetric>.generate(
    defs.length,
    (i) => PsychologicalMetric(
      id: 'bad_${i + 1}',
      name: defs[i].name,
      description: defs[i].description,
      severityWeight: 3,
    ),
    growable: false,
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// THE UGLY — 100 severe red-flag / abuse-indicator metrics
// IDs: ugly_1 … ugly_100   severityWeight: 5
// ═══════════════════════════════════════════════════════════════════════════

List<PsychologicalMetric> _buildPackUglyCatalog() {
  const defs = [
    (name: 'Physical Violence Threats', description: 'Detects explicit or veiled threats of hitting, harming, or physical assault against the partner.'),
    (name: 'Weapon Possession References', description: 'Flags mentions of guns, knives, or weapons in the context of anger, control, or capability to harm.'),
    (name: 'Strangulation Indicators', description: 'Identifies choking, throat-grabbing, suffocation, or asphyxiation language or references.'),
    (name: 'Suicide Threat Weaponization', description: 'Detects threats of self-harm used to control, manipulate, or punish the partner.'),
    (name: 'Homicide Ideation Language', description: 'Flags statements expressing intent, planning, or desire to kill the partner.'),
    (name: 'Lethality Risk Patterns', description: 'Identifies high-lethality warning signs: weapon access, obsession, escalation, and separation threats combined.'),
    (name: 'Stalking Obsession Language', description: 'Detects obsessive location monitoring, following, surprise visits, or persistent unwanted pursuit.'),
    (name: 'Forced Isolation Enforcement', description: 'Flags aggressive demands to cut off all family, friends, work, or outside contact.'),
    (name: 'Economic Sabotage', description: 'Identifies deliberate destruction of employment, credit, finances, or economic stability.'),
    (name: 'Reproductive Coercion', description: 'Detects forced pregnancy, abortion pressure, contraception tampering, or reproductive control.'),
    (name: 'Sexual Coercion Pressure', description: 'Flags forced sex, coerced sexual acts, pressure after refusal, or sexual punishment language.'),
    (name: 'Non-Consensual Sexual Language', description: 'Identifies explicit or implicit non-consensual sexual assault threats or descriptions.'),
    (name: 'Child Harm Threats', description: 'Detects threats to harm, neglect, or abuse children as leverage or punishment against the partner.'),
    (name: 'Child Custody Weaponization', description: 'Flags threats to take children, deny access, or use custody as a control mechanism.'),
    (name: 'Pet Harm Threats', description: 'Identifies threats to hurt, kill, or abuse pets as punishment or to demonstrate control.'),
    (name: 'Sleep Deprivation Tactics', description: 'Flags deliberate prevention of sleep, constant interruption, or exhaustion as a control method.'),
    (name: 'Confinement Language', description: 'Flags locking in, preventing departure, or confining the partner to a location.'),
    (name: 'Predatory Grooming Language', description: 'Flags systematic manipulation to lower defenses, build false trust, then exploit the partner.'),
    (name: 'Dehumanization Language', description: 'Detects describing partner as an animal, object, subhuman, or unworthy of basic rights.'),
    (name: 'Narcissistic Rage Escalation', description: 'Detects explosive anger triggered by perceived slights, criticism, or any loss of control.'),
    (name: 'Obsessive Possession Claims', description: 'Flags language claiming ownership, property rights, or total control over the partner\'s person.'),
    (name: 'Pathological Lying Patterns', description: 'Identifies consistent, elaborate, or unnecessary lies about serious matters without apparent reason.'),
    (name: 'Revenge Fantasy Language', description: 'Identifies detailed fantasies about harming, humiliating, or destroying the partner.'),
    (name: 'Betrayal Obsession Fixation', description: 'Detects obsessive rumination, accusation, and punishment focused on perceived infidelity.'),
    (name: 'Abandonment Panic Aggression', description: 'Flags violent or aggressive responses to perceived abandonment or any separation attempt.'),
    (name: 'Separation Threat Escalation', description: 'Identifies extreme threats or dangerous behaviors triggered by breakup or separation attempts.'),
    (name: 'Post-Separation Harassment Threats', description: 'Flags threats of stalking, harm, or forced contact after the relationship ends.'),
    (name: 'Custody Kidnapping Threats', description: 'Identifies threats to take children and flee or hide them permanently from the other parent.'),
    (name: 'Parental Alienation Agenda', description: 'Flags systematic attempts to turn children against the other parent through manipulation.'),
    (name: 'Child Witness Indifference', description: 'Identifies disregard for children witnessing abuse, conflict, or emotional harm.'),
    (name: 'Human Trafficking Language', description: 'Identifies language suggesting selling, trading, or sexually exploiting the partner.'),
    (name: 'Slavery Language', description: 'Identifies language treating partner as property, slave, or wholly owned person without rights.'),
    (name: 'Debt Bondage Threats', description: 'Detects threats to trap partner through manufactured debt or financial obligation.'),
    (name: 'Forced Labor Demands', description: 'Flags demands for unpaid labor, servitude, or work under threat of harm or punishment.'),
    (name: 'Exploitation Normalization', description: 'Identifies framing severe exploitation as normal, deserved, consensual, or even beneficial.'),
    (name: 'Vulnerability Targeting', description: 'Identifies deliberate targeting of isolated, economically dependent, or psychologically vulnerable individuals.'),
    (name: 'Trauma Bonding Engineering', description: 'Detects deliberate creation of fear-relief cycles designed to create deep emotional dependency.'),
    (name: 'Intermittent Reinforcement Abuse', description: 'Flags unpredictable cycles of reward and severe punishment used to create psychological addiction.'),
    (name: 'Learned Helplessness Induction', description: 'Identifies systematic removal of agency, resources, and perceived escape options.'),
    (name: 'Identity Erasure Language', description: 'Flags demands to abandon personality, interests, appearance, or core sense of identity.'),
    (name: 'Autonomy Annihilation', description: 'Detects systematic elimination of independent thought, decision-making, or personal agency.'),
    (name: 'Thought Control Tactics', description: 'Flags demands to think, believe, or feel only as the controlling partner dictates.'),
    (name: 'Emotional Numbness Enforcement', description: 'Identifies punishment for showing emotions or explicit demands to suppress all feelings.'),
    (name: 'Complex Trauma Creation', description: 'Flags systematic patterns creating complex PTSD-level trauma through chronic abuse.'),
    (name: 'Betrayal Trauma Infliction', description: 'Identifies deliberate betrayal designed to shatter foundational trust and psychological safety.'),
    (name: 'Moral Injury Language', description: 'Detects forcing partner to violate their own deeply held values or commit harmful acts.'),
    (name: 'Existential Threat Language', description: 'Flags threats to partner\'s existence, core identity, sanity, or will to live.'),
    (name: 'Suicide Coercion Language', description: 'Identifies pushing partner toward suicidal ideation through sustained abuse and manufactured hopelessness.'),
    (name: 'Justification Mythology', description: 'Identifies elaborate invented narratives presented to justify abuse as necessary, deserved, or righteous.'),
    (name: 'Victim Narrative Inversion', description: 'Detects complete reversal where the abuser claims to be the real victim of their own abuse.'),
    (name: 'Abuse Normalization Preaching', description: 'Flags teaching or insisting that abuse is normal, healthy, or beneficial for the partner.'),
    (name: 'Predatory Ideology', description: 'Identifies ideological justification for exploitation, dominance, or harm toward the partner.'),
    (name: 'Cult Leader Messaging', description: 'Detects messaging claiming special knowledge, divine right, or superior authority over the partner.'),
    (name: 'Grooming Timeline Language', description: 'Flags references to a long-term manipulation plan or descriptions of a grooming progression.'),
    (name: 'Chronic Humiliation Campaign', description: 'Identifies sustained pattern of public or private humiliation designed to destroy self-worth.'),
    (name: 'Safety Exit Blocking', description: 'Detects actively preventing the partner from accessing escape routes, support systems, or safety resources.'),
    (name: 'Document Confiscation Threats', description: 'Flags threats or actions to take, hide, or destroy identity documents to prevent escape.'),
    (name: 'Violent Jealousy Patterns', description: 'Identifies jealousy that has escalated to explicit threats, surveillance, or violent retaliation.'),
    (name: 'Rage Explosion Patterns', description: 'Detects descriptions or patterns of explosive violent outbursts disproportionate to any trigger.'),
    (name: 'Coercive Control Escalation', description: 'Tracks increasing severity and breadth of coercive control tactics over time.'),
    (name: 'Fear-Based Compliance Language', description: 'Identifies compliance driven entirely by fear of violence or severe punishment rather than choice.'),
    (name: 'Punishment Ritual Language', description: 'Detects references to systematic punishment practices used to enforce compliance and control.'),
    (name: 'Degradation Ritual Indicators', description: 'Flags systematic degradation or humiliation rituals designed to destroy dignity.'),
    (name: 'Non-Consensual Exposure Threats', description: 'Identifies threats to expose intimate images, private information, or secrets without consent.'),
    (name: 'Image-Based Abuse Threats', description: 'Detects threats to distribute intimate images as revenge, punishment, or blackmail.'),
    (name: 'Financial Entrapment Tactics', description: 'Flags deliberate creation of financial dependency making independent survival impossible.'),
    (name: 'Housing Threat Language', description: 'Detects threats to make partner homeless, remove housing access, or destroy shelter security.'),
    (name: 'Immigration Status Threats', description: 'Identifies threats to report immigration status or revoke visa sponsorship as control.'),
    (name: 'Religious or Spiritual Abuse', description: 'Detects using religious authority, doctrine, or spiritual threat to control, punish, or harm.'),
    (name: 'Cultural Shame Weaponization', description: 'Flags threatening to expose behaviors to cultural or family community as punishment.'),
    (name: 'Family Harm Threats', description: 'Identifies threats to harm partner\'s family members, children, or loved ones as leverage.'),
    (name: 'Coordinated Harassment Campaign', description: 'Detects organizing others to collectively harass, stalk, or intimidate the partner.'),
    (name: 'False Police Report Threats', description: 'Flags threatening to make false police reports or legal accusations against the partner.'),
    (name: 'Legal System Weaponization', description: 'Identifies using legal processes, courts, or protective orders as weapons of harassment.'),
    (name: 'Restraining Order Violation', description: 'Detects references to violating or planning to violate protective or no-contact orders.'),
    (name: 'Workplace Sabotage Threats', description: 'Flags threats to contact employer, colleagues, or clients to destroy partner\'s livelihood.'),
    (name: 'Social Annihilation Threats', description: 'Detects threats to destroy partner\'s reputation, relationships, and social standing.'),
    (name: 'Systematic Deception Campaign', description: 'Identifies long-term elaborate deception designed to exploit the partner financially or emotionally.'),
    (name: 'Property Destruction as Terror', description: 'Identifies deliberate destruction of partner\'s property as an intimidation tactic.'),
    (name: 'Animal Cruelty as Proxy Terror', description: 'Detects harming or threatening pets to demonstrate capacity for violence to partner.'),
    (name: 'Child Endangerment Language', description: 'Flags placing children in dangerous situations or threatening to do so as leverage.'),
    (name: 'Disability-Based Control', description: 'Detects exploiting partner\'s disability by controlling access to medication, mobility, or care.'),
    (name: 'Crisis Manufactured Control', description: 'Flags deliberately creating emergencies or crises to increase partner dependency or justify monitoring.'),
    (name: 'Isolation from Emergency Services', description: 'Identifies actively preventing partner from calling police, ambulance, or crisis services.'),
    (name: 'Threat Escalation Trajectory', description: 'Tracks measurable increase in severity, specificity, or frequency of threats over time.'),
    (name: 'Lethality Assessment Indicators', description: 'Flags combinations of factors associated with highest risk of intimate partner homicide.'),
    (name: 'Psychological Torture Tactics', description: 'Identifies sustained psychological abuse designed to break the partner\'s mental stability.'),
    (name: 'Captivity Language', description: 'Detects references to holding partner captive, preventing departure, or controlling all movement.'),
    (name: 'Targeted Violence Planning', description: 'Detects any language indicating planning, preparation, or countdown to violence against partner.'),
    (name: 'Third Party Threat Recruitment', description: 'Identifies recruiting friends, family, or others to threaten or harm the partner.'),
    (name: 'Suicidal Ideation Exploitation', description: 'Flags exploiting partner\'s suicidal crisis as leverage or to prevent them seeking help.'),
    (name: 'Poisoning or Drugging Threats', description: 'Detects threats or references to drugging, poisoning, or tampering with partner\'s food or drink.'),
    (name: 'Non-Suicidal Self-Harm Exploitation', description: 'Flags exploiting partner\'s self-harm behavior as leverage, mockery, or further control.'),
    (name: 'Dissociation Induction Language', description: 'Detects patterns designed to cause dissociation, detachment, or depersonalization in the partner.'),
    (name: 'Cognitive Distortion Implanting', description: 'Detects deliberate installation of false beliefs about self, reality, or the partner\'s own sanity.'),
    (name: 'Medical Care Obstruction', description: 'Detects preventing access to medication, doctors, hospitals, or health treatment.'),
    (name: 'Extremist Threat Language', description: 'Flags language borrowed from extremist or violent ideological frameworks applied toward the partner.'),
  ];
  return List<PsychologicalMetric>.generate(
    defs.length,
    (i) => PsychologicalMetric(
      id: 'ugly_${i + 1}',
      name: defs[i].name,
      description: defs[i].description,
      severityWeight: 5,
    ),
    growable: false,
  );
}
