import 'dart:async';

import 'dart:io';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:printing/printing.dart';
import 'package:which_partner_is_toxic/controllers/toxicity_analyzer_controller.dart';
import 'package:which_partner_is_toxic/models.dart';
import 'package:which_partner_is_toxic/widgets/membership_landing_page.dart';

class ReportViewerPane extends StatelessWidget {
  const ReportViewerPane({super.key});

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Theme.of(context).colorScheme.surfaceContainerHighest,
      child: SafeArea(
        child: Consumer<ToxicityAnalyzerController>(
          builder: (context, controller, child) {
            if (controller.isAnalyzing) {
              return const _AnalysisLoadingView();
            }

            final report = controller.activeReport;
            if (report != null) {
              return _AnalysisReportView(
                report: report,
                pdfBytes: controller.activePdfBytes,
                errorMessage: controller.errorMessage,
              );
            }

            return _EmptyReportView(
              statusMessage: controller.statusMessage,
              errorMessage: controller.errorMessage,
              hasActiveThread: controller.activeThread != null,
              selectedMetricCount: controller.selectedMetricCount,
            );
          },
        ),
      ),
    );
  }
}

class _AnalysisLoadingView extends StatefulWidget {
  const _AnalysisLoadingView();

  @override
  State<_AnalysisLoadingView> createState() => _AnalysisLoadingViewState();
}

class _AnalysisLoadingViewState extends State<_AnalysisLoadingView>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(milliseconds: 1500),
      vsync: this,
    )..repeat(reverse: true);
    _fadeAnimation = Tween<double>(
      begin: 0.4,
      end: 1.0,
    ).animate(CurvedAnimation(parent: _controller, curve: Curves.easeInOut));
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: FadeTransition(
        opacity: _fadeAnimation,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 48, vertical: 32),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: Colors.blue, width: 3),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withValues(alpha: 0.3),
                blurRadius: 20,
                spreadRadius: 5,
              ),
            ],
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Colors.red),
                strokeWidth: 4,
              ),
              const SizedBox(height: 24),
              Text(
                'Stand by while your psychological\nanalysis is Generated by AI.',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: Colors.red,
                  shadows: [
                    Shadow(
                      color: Colors.blue,
                      offset: const Offset(2, 2),
                      blurRadius: 3,
                    ),
                    Shadow(
                      color: Colors.blue,
                      offset: const Offset(-1, -1),
                      blurRadius: 3,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _AnalysisReportView extends StatefulWidget {
  final PsychologicalAnalysisReport report;
  final Uint8List? pdfBytes;
  final String? errorMessage;

  const _AnalysisReportView({
    required this.report,
    required this.pdfBytes,
    required this.errorMessage,
  });

  @override
  State<_AnalysisReportView> createState() => _AnalysisReportViewState();
}

class _AnalysisReportViewState extends State<_AnalysisReportView> {
  bool _isPdfPreviewOpen = false;
  bool _debugBlurDisabled = false;

  @override
  Widget build(BuildContext context) {
    final report = widget.report;
    final pdfBytes = widget.pdfBytes;
    final controller = context.watch<ToxicityAnalyzerController>();
    final canAccessFullReport =
        controller.canAccessFullCurrentReport || _debugBlurDisabled;

    return Focus(
      autofocus: true,
      onKeyEvent: (node, event) {
        if (event is KeyDownEvent &&
            event.logicalKey == LogicalKeyboardKey.keyH &&
            HardwareKeyboard.instance.isControlPressed &&
            HardwareKeyboard.instance.isAltPressed) {
          setState(() {
            _debugBlurDisabled = !_debugBlurDisabled;
          });
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                _debugBlurDisabled
                    ? 'Debug: Blur disabled'
                    : 'Debug: Blur enabled',
              ),
              duration: const Duration(seconds: 1),
            ),
          );
          return KeyEventResult.handled;
        }
        return KeyEventResult.ignored;
      },
      child: Stack(
        children: [
          Positioned.fill(
            child: SingleChildScrollView(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 96),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  _PdfStatusCard(
                    pdfBytes: pdfBytes,
                    errorMessage: widget.errorMessage,
                  ),
                  const SizedBox(height: 16),
                  if (pdfBytes != null) ...[
                    _PdfActionCard(pdfBytes: pdfBytes, controller: controller),
                    const SizedBox(height: 16),
                    _PdfPreviewToggleCard(
                      isOpen: _isPdfPreviewOpen,
                      canAccessFullReport: canAccessFullReport,
                      onPressed: () {
                        if (!canAccessFullReport) {
                          _openMembershipLandingPage(context);
                          return;
                        }
                        setState(() => _isPdfPreviewOpen = !_isPdfPreviewOpen);
                      },
                    ),
                    const SizedBox(height: 8),
                    if (canAccessFullReport)
                      AnimatedCrossFade(
                        firstChild: const SizedBox.shrink(),
                        secondChild: SizedBox(
                          height: 620,
                          child: Card(
                            clipBehavior: Clip.antiAlias,
                            child: PdfPreview(
                              build: (format) async => pdfBytes,
                              canChangeOrientation: false,
                              canChangePageFormat: false,
                              allowSharing: true,
                              allowPrinting: true,
                              pdfFileName: 'relationship_analysis_report.pdf',
                            ),
                          ),
                        ),
                        crossFadeState: _isPdfPreviewOpen
                            ? CrossFadeState.showSecond
                            : CrossFadeState.showFirst,
                        duration: const Duration(milliseconds: 260),
                      ),
                    const SizedBox(height: 16),
                  ],
                  _ReportSectionCard(
                    title: 'Executive Summary',
                    obscureContent: !canAccessFullReport,
                    visiblePreviewHeight: 44,
                    child: Text(report.executiveSummary),
                  ),
                  const SizedBox(height: 16),
                  _LockedReportSectionStack(
                    canAccessFullReport: canAccessFullReport,
                    children: [
                      _ReportSectionCard(
                        title: 'Metric Scores',
                        obscureContent: !canAccessFullReport,
                        visiblePreviewHeight: 28,
                        child: Column(
                          children: report.metricScores.entries
                              .map(
                                (entry) => _MetricScoreRow(
                                  metricName: entry.key,
                                  score: entry.value,
                                ),
                              )
                              .toList(),
                        ),
                      ),
                      const SizedBox(height: 16),
                      _ReportSectionCard(
                        title: 'Contextual Evidence Examples',
                        obscureContent: !canAccessFullReport,
                        visiblePreviewHeight: 28,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: report.evidenceExamples
                              .map(
                                (example) =>
                                    _EvidenceExampleTile(example: example),
                              )
                              .toList(),
                        ),
                      ),
                      if (report.forensicVerdict.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        _ReportSectionCard(
                          title: 'Neutral Synthesis',
                          obscureContent: !canAccessFullReport,
                          visiblePreviewHeight: 28,
                          child: Text(report.forensicVerdict),
                        ),
                      ],
                      if (report.partnerOneAnalysis.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        _ReportSectionCard(
                          title: 'Analysis of ${report.senderName} (Sender)',
                          obscureContent: !canAccessFullReport,
                          visiblePreviewHeight: 28,
                          child: Text(report.partnerOneAnalysis),
                        ),
                      ],
                      if (report.partnerTwoAnalysis.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        _ReportSectionCard(
                          title:
                              'Analysis of ${report.receiverName} (Receiver)',
                          obscureContent: !canAccessFullReport,
                          visiblePreviewHeight: 28,
                          child: Text(report.partnerTwoAnalysis),
                        ),
                      ],
                      if (report.primaryProblemConclusion.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        _ReportSectionCard(
                          title: 'Final Conclusion',
                          obscureContent: !canAccessFullReport,
                          visiblePreviewHeight: 28,
                          child: Text(report.primaryProblemConclusion),
                        ),
                      ],
                    ],
                  ),
                ],
              ),
            ),
          ),
          if (!canAccessFullReport)
            Center(
              child: Card(
                elevation: 8,
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 2),
                  child: ElevatedButton.icon(
                    onPressed: () => _openMembershipLandingPage(context),
                    icon: const Icon(Icons.lock_open),
                    label: const Text(
                      'Unlock and show this entire report',
                      textAlign: TextAlign.center,
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _EvidenceExampleTile extends StatelessWidget {
  final ContextualEvidenceExample example;

  const _EvidenceExampleTile({required this.example});

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '${example.speaker}: ${example.behavior}',
            style: textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 4),
          Text(example.context),
          const SizedBox(height: 4),
          Text(
            '"${example.quote}"',
            style: textTheme.bodyMedium?.copyWith(fontStyle: FontStyle.italic),
          ),
        ],
      ),
    );
  }
}

class _LockedReportSectionStack extends StatelessWidget {
  final bool canAccessFullReport;
  final List<Widget> children;

  const _LockedReportSectionStack({
    required this.canAccessFullReport,
    required this.children,
  });

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      ignoring: !canAccessFullReport,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: children,
      ),
    );
  }
}

class _PdfPreviewToggleCard extends StatelessWidget {
  final bool isOpen;
  final bool canAccessFullReport;
  final VoidCallback onPressed;

  const _PdfPreviewToggleCard({
    required this.isOpen,
    required this.canAccessFullReport,
    required this.onPressed,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      child: ListTile(
        leading: Icon(
          isOpen ? Icons.unfold_less : Icons.open_in_full,
          color: Theme.of(context).colorScheme.primary,
        ),
        title: Text(
          isOpen ? 'Close PDF Preview Window' : 'Open PDF Preview Window',
        ),
        subtitle: const Text(
          'The embedded PDF window starts closed to keep the report compact.',
        ),
        trailing: IconButton(
          onPressed: onPressed,
          icon: Icon(
            isOpen ? Icons.keyboard_arrow_up : Icons.keyboard_arrow_down,
          ),
        ),
        onTap: onPressed,
      ),
    );
  }
}

class _PdfActionCard extends StatelessWidget {
  final Uint8List pdfBytes;
  final ToxicityAnalyzerController controller;

  const _PdfActionCard({required this.pdfBytes, required this.controller});

  @override
  Widget build(BuildContext context) {
    final canAccessFullReport = controller.canAccessFullCurrentReport;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Wrap(
          spacing: 12,
          runSpacing: 12,
          children: [
            FilledButton.icon(
              onPressed: () async {
                if (!canAccessFullReport) {
                  _openMembershipLandingPage(context);
                  return;
                }

                final temporaryDirectory = await getTemporaryDirectory();
                final pdfFile = File(
                  '${temporaryDirectory.path}/relationship_analysis_report.pdf',
                );
                await pdfFile.writeAsBytes(pdfBytes, flush: true);
                await OpenFilex.open(pdfFile.path);
              },
              icon: const Icon(Icons.open_in_new),
              label: const Text('Open PDF'),
            ),
            OutlinedButton.icon(
              onPressed: () {
                if (!canAccessFullReport) {
                  _openMembershipLandingPage(context);
                  return;
                }

                Printing.sharePdf(
                  bytes: pdfBytes,
                  filename: 'relationship_analysis_report.pdf',
                );
              },
              icon: const Icon(Icons.ios_share),
              label: const Text('Share PDF'),
            ),
            OutlinedButton.icon(
              onPressed: () {
                if (!canAccessFullReport) {
                  _openMembershipLandingPage(context);
                  return;
                }

                Printing.layoutPdf(
                  name: 'relationship_analysis_report.pdf',
                  onLayout: (format) async => pdfBytes,
                );
              },
              icon: const Icon(Icons.print),
              label: const Text('Print PDF'),
            ),
          ],
        ),
      ),
    );
  }
}

void showPremiumUpsellDialog(BuildContext context) {
  showDialog<void>(
    context: context,
    builder: (dialogContext) {
      return AlertDialog(
        title: const Text('Unlock Full Forensic Reports'),
        content: const SizedBox(
          width: 720,
          child: Text(
            'Unlock this single report for \$20 with no subscription, choose Standard for full SMS reports with 10 reports per 24 hours, or choose Pro Membership for LinkedIn, WhatsApp, Instagram, Facebook Messenger, Telegram, Email, and Calendar imports with no daily limit on reports run.',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () async {
              Navigator.of(dialogContext).pop();
              final controller = context.read<ToxicityAnalyzerController>();
              if (controller.isPremiumUnlocked ||
                  controller.isConnectedAccountsUnlocked ||
                  controller.isCurrentReportUnlocked) {
                return;
              }

              final pressCount = await controller.recordNotNowPress();
              if (context.mounted && pressCount == 3) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    duration: const Duration(seconds: 60),
                    content: _DiscountCountdownSnackBar(
                      onUnlock: () {
                        controller.unlockCurrentReport();
                        ScaffoldMessenger.of(context).hideCurrentSnackBar();
                      },
                    ),
                  ),
                );
              }
            },
            child: const Text('Not now'),
          ),
          OutlinedButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              _handleInstantUnlock(context);
            },
            child: const Text('Unlock This Report - \$20'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              _openMembershipLandingPage(context);
            },
            child: const Text('Join Standard - \$9.99/mo'),
          ),
          FilledButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              _openMembershipLandingPage(context);
            },
            child: const Text('Pro Membership - \$19.99/mo'),
          ),
        ],
      );
    },
  );
}

void _handleInstantUnlock(BuildContext context) {
  showDialog<void>(
    context: context,
    builder: (dialogContext) {
      return AlertDialog(
        title: const Text('Instant Report Unlock - \$20'),
        content: const Text(
          'This is a one-time purchase to unlock the current report only. No subscription required. Future reports will require separate unlocks or a membership.\n\nProceed with payment?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              final controller = context.read<ToxicityAnalyzerController>();
              controller.unlockCurrentReport();
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text(
                    'Report unlocked! (Payment integration pending)',
                  ),
                  duration: Duration(seconds: 3),
                ),
              );
            },
            child: const Text('Purchase for \$20'),
          ),
        ],
      );
    },
  );
}

void _openMembershipLandingPage(BuildContext context) {
  Navigator.of(context).push(
    MaterialPageRoute<void>(
      builder: (context) => const MembershipLandingPage(),
    ),
  );
}

class _DiscountCountdownSnackBar extends StatefulWidget {
  final VoidCallback onUnlock;

  const _DiscountCountdownSnackBar({required this.onUnlock});

  @override
  State<_DiscountCountdownSnackBar> createState() =>
      _DiscountCountdownSnackBarState();
}

class _DiscountCountdownSnackBarState
    extends State<_DiscountCountdownSnackBar> {
  Timer? _timer;
  int _secondsRemaining = 60;

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (_secondsRemaining <= 1) {
        timer.cancel();
        if (mounted) {
          setState(() => _secondsRemaining = 0);
        }
        return;
      }

      if (mounted) {
        setState(() => _secondsRemaining -= 1);
      }
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: Text(
            'Limited demo offer: reveal this full analysis for \$10. Expires in $_secondsRemaining seconds.',
          ),
        ),
        TextButton(
          onPressed: _secondsRemaining > 0 ? widget.onUnlock : null,
          child: const Text('Unlock for \$10'),
        ),
      ],
    );
  }
}

class _PdfStatusCard extends StatelessWidget {
  final Uint8List? pdfBytes;
  final String? errorMessage;

  const _PdfStatusCard({required this.pdfBytes, required this.errorMessage});

  @override
  Widget build(BuildContext context) {
    final hasPdf = pdfBytes != null && pdfBytes!.isNotEmpty;
    final colorScheme = Theme.of(context).colorScheme;

    return Card(
      color: hasPdf ? colorScheme.primaryContainer : colorScheme.errorContainer,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Text(
          hasPdf
              ? 'PDF generated successfully (${pdfBytes!.length} bytes). If the preview area below is blank, use the print/share controls or try a desktop/browser target.'
              : errorMessage ?? 'PDF has not been generated for this report.',
        ),
      ),
    );
  }
}

class _MetricScoreRow extends StatelessWidget {
  final String metricName;
  final double score;

  const _MetricScoreRow({required this.metricName, required this.score});

  @override
  Widget build(BuildContext context) {
    final normalizedScore = score.clamp(0.0, 1.0);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(child: Text(metricName)),
              Text(normalizedScore.toStringAsFixed(2)),
            ],
          ),
          const SizedBox(height: 6),
          LinearProgressIndicator(value: normalizedScore),
        ],
      ),
    );
  }
}

class _ReportSectionCard extends StatelessWidget {
  final String title;
  final Widget child;
  final bool obscureContent;
  final double visiblePreviewHeight;

  const _ReportSectionCard({
    required this.title,
    required this.child,
    this.obscureContent = false,
    this.visiblePreviewHeight = 28,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 12),
            obscureContent
                ? _ObscuredReportContent(
                    visiblePreviewHeight: visiblePreviewHeight,
                    child: child,
                  )
                : child,
          ],
        ),
      ),
    );
  }
}

class _ObscuredReportContent extends StatefulWidget {
  final Widget child;
  final double visiblePreviewHeight;

  const _ObscuredReportContent({
    required this.child,
    required this.visiblePreviewHeight,
  });

  @override
  State<_ObscuredReportContent> createState() => _ObscuredReportContentState();
}

class _ObscuredReportContentState extends State<_ObscuredReportContent> {
  final GlobalKey _childKey = GlobalKey();
  double? _blurStartPosition;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _measureChild();
    });
  }

  void _measureChild() {
    final RenderBox? renderBox =
        _childKey.currentContext?.findRenderObject() as RenderBox?;
    if (renderBox != null && mounted) {
      final height = renderBox.size.height;
      setState(() {
        _blurStartPosition = height * 0.25;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return ClipRect(
      child: Stack(
        children: [
          KeyedSubtree(key: _childKey, child: widget.child),
          if (_blurStartPosition != null)
            Positioned(
              left: 0,
              right: 0,
              top: _blurStartPosition,
              bottom: 0,
              child: ClipRect(
                child: BackdropFilter(
                  filter: ImageFilter.blur(sigmaX: 4, sigmaY: 4),
                  child: Container(
                    color: colorScheme.surface.withValues(alpha: 0.4),
                    width: double.infinity,
                    height: double.infinity,
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _EmptyReportView extends StatelessWidget {
  final String? statusMessage;
  final String? errorMessage;
  final bool hasActiveThread;
  final int selectedMetricCount;

  const _EmptyReportView({
    required this.statusMessage,
    required this.errorMessage,
    required this.hasActiveThread,
    required this.selectedMetricCount,
  });

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.picture_as_pdf_outlined,
                  size: 48,
                  color: Theme.of(context).colorScheme.primary,
                ),
                const SizedBox(height: 16),
                Text(
                  'Report Viewer / PDF Engine',
                  style: Theme.of(context).textTheme.titleLarge,
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 8),
                Text(
                  errorMessage ??
                      statusMessage ??
                      'Generated AI analysis and forensic PDF output will render here.',
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 16),
                Text(
                  'Loaded conversation: ${hasActiveThread ? 'yes' : 'no'}\nSelected metrics: $selectedMetricCount/${ToxicityAnalyzerController.requiredMetricSelectionCount}',
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
