import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class DisclaimerScreen extends StatefulWidget {
  final VoidCallback onAccepted;

  const DisclaimerScreen({super.key, required this.onAccepted});

  @override
  State<DisclaimerScreen> createState() => _DisclaimerScreenState();
}

class _DisclaimerScreenState extends State<DisclaimerScreen> {
  bool _hasScrolledToBottom = false;
  bool _checkboxAccepted = false;
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_onScroll);
  }

  @override
  void dispose() {
    _scrollController.removeListener(_onScroll);
    _scrollController.dispose();
    super.dispose();
  }

  void _onScroll() {
    if (!_hasScrolledToBottom) {
      final maxScroll = _scrollController.position.maxScrollExtent;
      final currentScroll = _scrollController.position.pixels;
      if (currentScroll >= maxScroll - 40) {
        setState(() => _hasScrolledToBottom = true);
      }
    }
  }

  Future<void> _accept() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('disclaimer_accepted', true);
    widget.onAccepted();
  }

  Future<void> _decline() async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        title: const Text('Cannot Continue'),
        content: const Text(
          'You must accept the disclaimer to use AIRTA. '
          'The app will now close.',
        ),
        actions: [
          FilledButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Go Back'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final canAccept = _hasScrolledToBottom && _checkboxAccepted;
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 24, horizontal: 20),
              decoration: BoxDecoration(
                color: colorScheme.errorContainer.withOpacity(0.3),
                border: Border(
                  bottom: BorderSide(color: colorScheme.error.withOpacity(0.3)),
                ),
              ),
              child: Column(
                children: [
                  Icon(Icons.warning_amber_rounded,
                      size: 48, color: colorScheme.error),
                  const SizedBox(height: 12),
                  Text(
                    'Medical & Liability Disclaimer',
                    style: Theme.of(context).textTheme.titleLarge?.copyWith(
                          fontWeight: FontWeight.bold,
                          color: colorScheme.error,
                        ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 6),
                  Text(
                    'Please read carefully before continuing',
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: colorScheme.onSurface.withOpacity(0.6),
                        ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                controller: _scrollController,
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _Section(
                      icon: Icons.info_outline,
                      title: 'For Entertainment Purposes Only',
                      body:
                          'AIRTA – AI Relationship Analyzer is provided for entertainment and informational purposes only. The analyses, reports, scores, and all other outputs generated by this application do not constitute medical advice, psychological advice, mental health treatment, clinical diagnosis, or therapy of any kind.',
                    ),
                    _Section(
                      icon: Icons.person_search,
                      title: 'Not a Substitute for Professional Help',
                      body:
                          'AIRTA is not a substitute for professional mental health care. Nothing produced by this application should be interpreted as a clinical assessment, psychiatric evaluation, or therapeutic recommendation. If you are experiencing emotional distress, relationship abuse, or mental health concerns, please consult a licensed mental health professional such as a Licensed Psychologist, LCSW, LMFT, LPC, or Psychiatrist.',
                    ),
                    _CrisisBox(),
                    _Section(
                      icon: Icons.smart_toy_outlined,
                      title: 'AI Limitations',
                      body:
                          'Analysis is generated by artificial intelligence and may be inaccurate, incomplete, or misleading. The AI cannot fully account for tone, sarcasm, cultural nuance, or situational context. Results should never be used as evidence in legal, medical, or professional proceedings.',
                    ),
                    _Section(
                      icon: Icons.gavel,
                      title: 'Limitation of Liability',
                      body:
                          'To the fullest extent permitted by applicable law, AIRTA Corp, its officers, directors, employees, agents, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or reliance on the App or its outputs, any decisions made based on the analysis, or any relationship, personal, professional, or legal consequences resulting from use of this application.',
                    ),
                    _Section(
                      icon: Icons.check_circle_outline,
                      title: 'Your Acknowledgment',
                      body:
                          'By accepting, you confirm that:\n\n'
                          '• You are using this app solely for personal entertainment and informational purposes.\n\n'
                          '• You will not rely on the app\'s output to make important life decisions without consulting a qualified professional.\n\n'
                          '• You take full responsibility for any actions taken based on the app\'s output.\n\n'
                          '• You are of legal age in your jurisdiction to use this application.\n\n'
                          '• Use of this app does not create any professional relationship between you and AIRTA Corp.',
                    ),
                    const SizedBox(height: 8),
                    if (!_hasScrolledToBottom)
                      Center(
                        child: Text(
                          '↓ Scroll down to continue',
                          style: TextStyle(
                            color: colorScheme.primary,
                            fontSize: 13,
                          ),
                        ),
                      ),
                    const SizedBox(height: 16),
                  ],
                ),
              ),
            ),
            Container(
              padding: const EdgeInsets.fromLTRB(20, 12, 20, 20),
              decoration: BoxDecoration(
                color: colorScheme.surface,
                border: Border(
                  top: BorderSide(
                      color: colorScheme.outline.withOpacity(0.2)),
                ),
              ),
              child: Column(
                children: [
                  InkWell(
                    onTap: _hasScrolledToBottom
                        ? () => setState(
                            () => _checkboxAccepted = !_checkboxAccepted)
                        : null,
                    borderRadius: BorderRadius.circular(8),
                    child: Padding(
                      padding: const EdgeInsets.symmetric(vertical: 8),
                      child: Row(
                        children: [
                          Checkbox(
                            value: _checkboxAccepted,
                            onChanged: _hasScrolledToBottom
                                ? (val) => setState(
                                    () => _checkboxAccepted = val ?? false)
                                : null,
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              'I have read and accept the disclaimer. I understand this app is for entertainment purposes only and is not a substitute for professional mental health advice.',
                              style: TextStyle(
                                fontSize: 13,
                                color: _hasScrolledToBottom
                                    ? colorScheme.onSurface
                                    : colorScheme.onSurface.withOpacity(0.4),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: OutlinedButton(
                          onPressed: _decline,
                          style: OutlinedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            side: BorderSide(
                                color: colorScheme.error.withOpacity(0.5)),
                          ),
                          child: Text(
                            'Decline',
                            style: TextStyle(color: colorScheme.error),
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        flex: 2,
                        child: FilledButton(
                          onPressed: canAccept ? _accept : null,
                          style: FilledButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 14),
                          ),
                          child: const Text('I Accept — Continue'),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final IconData icon;
  final String title;
  final String body;

  const _Section({required this.icon, required this.title, required this.body});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 18, color: Theme.of(context).colorScheme.primary),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  title,
                  style: const TextStyle(
                      fontSize: 15, fontWeight: FontWeight.bold),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(body,
              style: TextStyle(
                  fontSize: 13.5,
                  color: Theme.of(context)
                      .colorScheme
                      .onSurface
                      .withOpacity(0.75),
                  height: 1.5)),
          const SizedBox(height: 8),
          Divider(color: Theme.of(context).colorScheme.outline.withOpacity(0.2)),
        ],
      ),
    );
  }
}

class _CrisisBox extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.red.withOpacity(0.08),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.red.withOpacity(0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Icon(Icons.emergency, color: Colors.red, size: 18),
              SizedBox(width: 8),
              Text('If You Are in Crisis',
                  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.red,
                      fontSize: 14)),
            ],
          ),
          const SizedBox(height: 10),
          _CrisisLine('National DV Hotline', '1-800-799-7233'),
          _CrisisLine('Crisis Text Line', 'Text HOME to 741741'),
          _CrisisLine('988 Suicide & Crisis Lifeline', 'Call or text 988'),
          _CrisisLine('Emergency Services', '911'),
        ],
      ),
    );
  }
}

class _CrisisLine extends StatelessWidget {
  final String label;
  final String value;
  const _CrisisLine(this.label, this.value);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: RichText(
        text: TextSpan(
          style: const TextStyle(fontSize: 13, color: Colors.red, height: 1.5),
          children: [
            TextSpan(
                text: '$label: ',
                style: const TextStyle(fontWeight: FontWeight.w600)),
            TextSpan(text: value),
          ],
        ),
      ),
    );
  }
}
