import sys
path = r'C:\My Projects\AIRTA\lib\widgets\user_account_page.dart'
with open(path, encoding='utf-8') as f:
    c = f.read()

original = c  # keep for diff check at end

# ── 1. Membership card: add red Upgrade button next to the tier pill
OLD_MEMBERSHIP_ROW = (
    "          Row(\n"
    "            children: [\n"
    "              Container(\n"
    "                padding:\n"
    "                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),\n"
    "                decoration: BoxDecoration(\n"
    "                  color: _tierColor(tier),\n"
    "                  borderRadius: BorderRadius.circular(6),\n"
    "                ),\n"
    "                child: Text(\n"
    "                  tier.displayName,\n"
    "                  style: const TextStyle(\n"
    "                      color: Colors.white,\n"
    "                      fontSize: 13,\n"
    "                      fontWeight: FontWeight.w700),\n"
    "                ),\n"
    "              ),\n"
    "              if (isTrialActive) ...[")

NEW_MEMBERSHIP_ROW = (
    "          Row(\n"
    "            children: [\n"
    "              Container(\n"
    "                padding:\n"
    "                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),\n"
    "                decoration: BoxDecoration(\n"
    "                  color: _tierColor(tier),\n"
    "                  borderRadius: BorderRadius.circular(6),\n"
    "                ),\n"
    "                child: Text(\n"
    "                  tier.displayName,\n"
    "                  style: const TextStyle(\n"
    "                      color: Colors.white,\n"
    "                      fontSize: 13,\n"
    "                      fontWeight: FontWeight.w700),\n"
    "                ),\n"
    "              ),\n"
    "              // Red Upgrade button for non-top tiers\n"
    "              if (tier == MembershipTier.standard ||\n"
    "                  tier == MembershipTier.free ||\n"
    "                  tier == MembershipTier.oneTimeUnlock) ...[  \n"
    "                const SizedBox(width: 8),\n"
    "                GestureDetector(\n"
    "                  onTap: () => Navigator.of(context).push(\n"
    "                    MaterialPageRoute(builder: (_) => const MembershipLandingPage()),\n"
    "                  ),\n"
    "                  child: Container(\n"
    "                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),\n"
    "                    decoration: BoxDecoration(\n"
    "                      color: const Color(0xFFcc0000),\n"
    "                      borderRadius: BorderRadius.circular(6),\n"
    "                    ),\n"
    "                    child: const Text(\n"
    "                      'Upgrade',\n"
    "                      style: TextStyle(\n"
    "                          color: Colors.white,\n"
    "                          fontSize: 12,\n"
    "                          fontWeight: FontWeight.w700),\n"
    "                    ),\n"
    "                  ),\n"
    "                ),\n"
    "              ],\n"
    "              if (isTrialActive) ...[")

assert OLD_MEMBERSHIP_ROW in c, "Membership row block not found"
c = c.replace(OLD_MEMBERSHIP_ROW, NEW_MEMBERSHIP_ROW, 1)
print("OK: Upgrade button added")

# ── 2. Replace the Metric Packs Purchased section
OLD_PACKS_SECTION = (
    "          // Metrics Packs Purchased Section\n"
    "          const Text(\n"
    "            'Metric Packs Purchased:',\n"
    "            style: TextStyle(\n"
    "              color: Color(0xFFd0d0ff),\n"
    "              fontSize: 14,\n"
    "              fontWeight: FontWeight.w600,\n"
    "            ),\n"
    "          ),\n"
    "          const SizedBox(height: 8),\n"
    "          if (purchasedPacks.isEmpty)\n"
    "            const Text(\n"
    "              'No metric packs purchased yet',\n"
    "              style: TextStyle(color: Color(0xFF6666aa), fontSize: 12),\n"
    "            )\n"
    "          else\n"
    "            ...purchasedPacks.map((packId) => Padding(\n"
    "              padding: const EdgeInsets.only(bottom: 6),\n"
    "              child: Row(\n"
    "                children: [\n"
    "                  const Icon(Icons.inventory_2, color: Color(0xFF6060ff), size: 18),\n"
    "                  const SizedBox(width: 10),\n"
    "                  Expanded(\n"
    "                    child: Text(\n"
    "                      packId,\n"
    "                      style: const TextStyle(color: Color(0xFFd0d0ff), fontSize: 13),\n"
    "                    ),\n"
    "                  ),\n"
    "                  Container(\n"
    "                    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),\n"
    "                    decoration: BoxDecoration(\n"
    "                      color: const Color(0xFF1a1a3a),\n"
    "                      borderRadius: BorderRadius.circular(4),\n"
    "                    ),\n"
    "                    child: const Text(\n"
    "                      'Owned',\n"
    "                      style: TextStyle(color: Color(0xFF6666aa), fontSize: 10),\n"
    "                    ),\n"
    "                  ),\n"
    "                ],\n"
    "              ),\n"
    "            )),")

NEW_PACKS_SECTION = (
    "          // Metrics Packs Purchased Section\n"
    "          const Text(\n"
    "            'Metric Packs Purchased:',\n"
    "            style: TextStyle(\n"
    "              color: Color(0xFFd0d0ff),\n"
    "              fontSize: 14,\n"
    "              fontWeight: FontWeight.w600,\n"
    "            ),\n"
    "          ),\n"
    "          const SizedBox(height: 8),\n"
    "          // Built-in expansion packs\n"
    "          ...[\n"
    "            if (_subService.isPackGoodUnlocked)\n"
    "              _buildPackRow('THE GOOD — Healthy Patterns', '100 Metrics', Icons.favorite, const Color(0xFF40aa40)),\n"
    "            if (_subService.isPackBadUnlocked)\n"
    "              _buildPackRow('THE BAD — Warning Signs', '100 Metrics', Icons.warning_amber_rounded, const Color(0xFFaaaa40)),\n"
    "            if (_subService.isPackUglyUnlocked)\n"
    "              _buildPackRow('THE UGLY — Abuse Indicators', '100 Metrics', Icons.dangerous, const Color(0xFFaa4040)),\n"
    "            if (_subService.isPackNarcissistUnlocked)\n"
    "              _buildPackRow('NARCISSIST Patterns', '50 Metrics', Icons.psychology, const Color(0xFF9040aa)),\n"
    "            if (_subService.isPackSerialKillerUnlocked)\n"
    "              _buildPackRow('SERIAL KILLER Patterns', '51 Metrics', Icons.crisis_alert, const Color(0xFFaa2020)),\n"
    "          ],\n"
    "          // User-submitted packs\n"
    "          if (purchasedPacks.isNotEmpty)\n"
    "            ...purchasedPacks.map((packId) {\n"
    "              final pack = _packsService.availablePacks\n"
    "                  .where((p) => p.id == packId)\n"
    "                  .firstOrNull;\n"
    "              return _buildPackRow(\n"
    "                pack?.packName ?? packId,\n"
    "                '${pack?.metricCount ?? 0} Metrics',\n"
    "                Icons.inventory_2,\n"
    "                const Color(0xFF6060ff),\n"
    "              );\n"
    "            }),\n"
    "          // Empty state\n"
    "          if (!_subService.isPackGoodUnlocked &&\n"
    "              !_subService.isPackBadUnlocked &&\n"
    "              !_subService.isPackUglyUnlocked &&\n"
    "              !_subService.isPackNarcissistUnlocked &&\n"
    "              !_subService.isPackSerialKillerUnlocked &&\n"
    "              purchasedPacks.isEmpty)\n"
    "            const Text(\n"
    "              'No metric packs purchased yet',\n"
    "              style: TextStyle(color: Color(0xFF6666aa), fontSize: 12),\n"
    "            ),")

assert OLD_PACKS_SECTION in c, "Packs section block not found"
c = c.replace(OLD_PACKS_SECTION, NEW_PACKS_SECTION, 1)
print("OK: Purchases section updated")

# ── 3. Fix _calculateTotalMetricsOwned
OLD_CALC = (
    "  int _calculateTotalMetricsOwned() {\n"
    "    // Base metrics + purchased packs + custom metrics\n"
    "    int total = 50; // Base free metrics\n"
    "    if (_subService.isPackGoodUnlocked) total += 100;\n"
    "    if (_subService.isPackBadUnlocked) total += 100;\n"
    "    if (_subService.isPackUglyUnlocked) total += 100;\n"
    "    if (_subService.isPackNarcissistUnlocked) total += 50;\n"
    "    if (_subService.isPackSerialKillerUnlocked) total += 50;\n"
    "    total += _packsService.purchasedPackIds.length * 25; // Avg 25 metrics per user pack\n"
    "    total += _packsService.getUserCustomMetricsCount();\n"
    "    return total;\n"
    "  }")

NEW_CALC = (
    "  int _calculateTotalMetricsOwned() {\n"
    "    // Base metrics + purchased packs + custom metrics\n"
    "    int total = 50;                                         // Base free metrics\n"
    "    if (_subService.isPackGoodUnlocked) total += 100;        // THE GOOD\n"
    "    if (_subService.isPackBadUnlocked) total += 100;         // THE BAD\n"
    "    if (_subService.isPackUglyUnlocked) total += 100;        // THE UGLY\n"
    "    if (_subService.isPackNarcissistUnlocked) total += 50;   // NARCISSIST\n"
    "    if (_subService.isPackSerialKillerUnlocked) total += 51; // SERIAL KILLER (51 metrics)\n"
    "    for (final packId in _packsService.purchasedPackIds) {\n"
    "      final pack = _packsService.availablePacks\n"
    "          .where((p) => p.id == packId)\n"
    "          .firstOrNull;\n"
    "      total += pack?.metricCount ?? 25;\n"
    "    }\n"
    "    total += _packsService.getUserCustomMetricsCount();\n"
    "    return total;\n"
    "  }")

assert OLD_CALC in c, "Calc block not found"
c = c.replace(OLD_CALC, NEW_CALC, 1)
print("OK: Total metrics count fixed")

# ── 4. Add _buildPackRow helper — insert after _calculateTotalMetricsOwned
INSERT_AFTER = "    return total;\n  }\n\n\n  Widget _buildEmailNotificationsCard()"
REPLACEMENT = (
    "    return total;\n"
    "  }\n"
    "\n"
    "  Widget _buildPackRow(String name, String subtitle, IconData icon, Color color) {\n"
    "    return Padding(\n"
    "      padding: const EdgeInsets.only(bottom: 8),\n"
    "      child: Row(\n"
    "        children: [\n"
    "          Icon(icon, color: color, size: 18),\n"
    "          const SizedBox(width: 10),\n"
    "          Expanded(\n"
    "            child: Column(\n"
    "              crossAxisAlignment: CrossAxisAlignment.start,\n"
    "              children: [\n"
    "                Text(name,\n"
    "                    style: const TextStyle(color: Color(0xFFd0d0ff), fontSize: 13)),\n"
    "                Text(subtitle,\n"
    "                    style: const TextStyle(color: Color(0xFF8888aa), fontSize: 11)),\n"
    "              ],\n"
    "            ),\n"
    "          ),\n"
    "          Container(\n"
    "            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),\n"
    "            decoration: BoxDecoration(\n"
    "              color: const Color(0xFF1a2a1a),\n"
    "              borderRadius: BorderRadius.circular(4),\n"
    "              border: Border.all(color: const Color(0xFF2a4a2a)),\n"
    "            ),\n"
    "            child: const Text('Owned',\n"
    "                style: TextStyle(color: Color(0xFF60cc60), fontSize: 10)),\n"
    "          ),\n"
    "        ],\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _buildEmailNotificationsCard()"
)

assert INSERT_AFTER in c, f"Insert anchor not found. Looking for: {repr(INSERT_AFTER)}"
c = c.replace(INSERT_AFTER, REPLACEMENT, 1)
print("OK: _buildPackRow helper added")

assert c != original, "No changes were made!"
with open(path, 'w', encoding='utf-8') as f:
    f.write(c)
print("\nAll 4 changes applied and saved.")
