// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'AI Relationship Toxicity Analyzer';

  @override
  String get psychologicalMetrics => 'Psychological Metrics';

  @override
  String get metricsDescription =>
      'Fewer selected metrics produce a deeper, more concentrated analysis of those behaviors. More selected metrics produce a broader report with less detail per metric.';

  @override
  String get selectSMS => 'Select SMS / RCS Chat';

  @override
  String get selectDiscordChannel => 'Select Discord Channel';

  @override
  String get lightMode => 'Light';

  @override
  String get darkMode => 'Dark';

  @override
  String get selectFile => 'Select file';

  @override
  String get analyzeSelectedMetrics => 'Analyze Selected metrics';

  @override
  String get analyze20RandomMetrics => 'Analyze 20 Random metrics';

  @override
  String get membershipOptions => 'Membership Options';

  @override
  String get free => 'Free';

  @override
  String get oneTimeUnlock => 'One-Time Report Unlock';

  @override
  String get standard => 'Standard';

  @override
  String get discordAddon => 'Discord Addon';

  @override
  String get analyze => 'Analyze';

  @override
  String get report => 'Report';

  @override
  String get pdfReport => 'PDF Report';

  @override
  String get openPdf => 'Open PDF';

  @override
  String get sharePdf => 'Share PDF';

  @override
  String get printPdf => 'Print PDF';

  @override
  String get closePdfPreview => 'Close PDF Preview Window';

  @override
  String get openPdfPreview => 'Open PDF Preview Window';

  @override
  String get pdfPreviewDescription =>
      'The embedded PDF window starts closed to keep the report compact.';

  @override
  String get notNow => 'Not now';

  @override
  String get unlockThisReport => 'Unlock This Report - \$20';

  @override
  String get joinStandard => 'Join Standard - \$9.99/mo';

  @override
  String get instantUnlockTitle => 'Instant Report Unlock - \$20';

  @override
  String get instantUnlockDescription =>
      'This is a one-time purchase to unlock the current report only. No subscription required. Future reports will require separate unlocks or a membership.\n\nProceed with payment?';

  @override
  String get purchaseFor20 => 'Purchase for \$20';

  @override
  String get share => 'Share';

  @override
  String get print => 'Print';

  @override
  String get save => 'Save';

  @override
  String get cancel => 'Cancel';

  @override
  String get ok => 'OK';

  @override
  String get loading => 'Loading...';

  @override
  String get error => 'Error';

  @override
  String get success => 'Success';

  @override
  String get conversations => 'Conversations';

  @override
  String get messages => 'Messages';

  @override
  String get selectConversation => 'Select Conversation';

  @override
  String get selectSmsConversation => 'Select SMS / RCS Conversation';

  @override
  String get searchConversations => 'Search conversations...';

  @override
  String get loadingConversations => 'Loading conversations...';

  @override
  String get errorLoadingConversations => 'Error Loading Conversations';

  @override
  String get selectConversationToAnalyze => 'Select conversation to analyze';

  @override
  String get analyzeWithSelectedMetrics => 'Analyze with the selected metrics';

  @override
  String get loadConversationAndSelectMetric =>
      'Load a conversation and select at least one metric';

  @override
  String get selectAtLeastOneMetric =>
      'At least one metric needs to be selected to run the report.';

  @override
  String get spinningMetricWheel => 'Spinning the metric wheel...';

  @override
  String get loadConversationToAnalyze => 'Load a conversation to analyze';

  @override
  String get noConversationsFound => 'No conversations found';

  @override
  String get permissionsRequired => 'Permissions Required';

  @override
  String get smsPermission => 'Text Messages';

  @override
  String get contactsPermission => 'Contacts';

  @override
  String get smsPermissionDescription =>
      'To analyze your SMS conversations for relationship patterns';

  @override
  String get contactsPermissionDescription =>
      'To display contact names instead of phone numbers';

  @override
  String get analyzingMessage =>
      'Stand by while your psychological analysis is generated by AI...';

  @override
  String get analyzingStatus => 'Analyzing conversation...';

  @override
  String get analyzingSubMessage =>
      'Please be patient, this process could take up to a minute depending on your connection speed and the quantity of selected metrics';

  @override
  String get unlockFullReport => 'Unlock and show this entire report';

  @override
  String get fullReportLocked => 'Full Report Locked';

  @override
  String get upgradeToUnlock =>
      'Upgrade your membership to unlock the full psychological analysis report with all metrics and detailed insights.';

  @override
  String get language => 'Language';

  @override
  String get english => 'English';

  @override
  String get spanish => 'Spanish';

  @override
  String get french => 'French';

  @override
  String get german => 'German';

  @override
  String get italian => 'Italian';

  @override
  String get portuguese => 'Portuguese';

  @override
  String get dutch => 'Dutch';

  @override
  String get russian => 'Russian';

  @override
  String get chinese => 'Chinese';

  @override
  String get japanese => 'Japanese';

  @override
  String get korean => 'Korean';

  @override
  String get arabic => 'Arabic';

  @override
  String get hindi => 'Hindi';

  @override
  String get turkish => 'Turkish';

  @override
  String get polish => 'Polish';

  @override
  String get ukrainian => 'Ukrainian';

  @override
  String get runAnotherAnalysis => 'Run another analysis?';

  @override
  String get becomeMemberTitle =>
      'Become a member to get the full analysis report';

  @override
  String get becomeMemberSubtitle =>
      'Choose the access level that matches the conversations and reports you need to analyze.';

  @override
  String get benefitAnalyzeSms => 'Analyze SMS text messages';

  @override
  String get benefitReportPreview => 'Run a report preview';

  @override
  String get benefitViewPartialReport => 'View about 25% of the report';

  @override
  String get benefitLockedDetails => 'Locked full report details';

  @override
  String get currentFreeAccess => 'Current free access';

  @override
  String get benefitUnlockCurrentReport => 'Unlock this current full report';

  @override
  String get benefitNoSubscription => 'No subscription';

  @override
  String get benefitSavePrintShareThis => 'Save, print, and share this report';

  @override
  String get benefitBestSingleAnalysis => 'Best if you only need one analysis';

  @override
  String get unlockThisReportShort => 'Unlock This Report';

  @override
  String get benefitFullSmsReport => 'Full SMS analysis report';

  @override
  String get benefitSavePrintSharePdf => 'Save, print, and share PDF reports';

  @override
  String get benefitTenReports => '10 reports per 24-hour period';

  @override
  String get benefitBestTextReview =>
      'Best for text-message relationship review';

  @override
  String get benefitDateRangeFilter => 'Filter analysis by date range';

  @override
  String get signUpStandard => 'Sign up for Standard Membership';

  @override
  String get benefitAddToStandard => 'Add to Standard membership';

  @override
  String get benefitAnalyzeDiscord => 'Analyze Discord server chats';

  @override
  String get benefitRequiresBot => 'Requires bot installation';

  @override
  String get benefitBestGamers => 'Best for gamers and Discord communities';

  @override
  String get addDiscordAnalysis => 'Add Discord Analysis';

  @override
  String get requiresStandardMembership => 'Requires Standard Membership';

  @override
  String get comingSoon => 'Coming Soon';

  @override
  String get comingSoonWithNextUpdate => 'Coming soon with next update:';

  @override
  String get proMembershipTier => 'Pro Membership Tier - \$19.99';

  @override
  String get proPlusMembershipTier => 'Pro-Plus Membership Tier - \$24.99';

  @override
  String get proGetsLabel => 'Pro gets:';

  @override
  String get proGetsDescription =>
      'Analyze chat threads from all the other popular texting and social media platforms such as:';

  @override
  String get proPlatformsList =>
      'LinkedIn, WhatsApp, Instagram, Facebook Messenger, Telegram, X (Twitter), Email, and Calendar';

  @override
  String get proPlusGetsLabel => 'Pro-Plus gets:';

  @override
  String get proPlusGetsDescription =>
      'Everything in Pro, plus the Discord addon at a reduced price.';

  @override
  String get purchaseSuccessfulUnlocked =>
      'Purchase successful! Report unlocked.';

  @override
  String get purchaseFailed => 'Purchase failed. Please try again.';

  @override
  String get membershipActivated => 'Membership activated!';

  @override
  String get dateRangeFilter => 'Date Range Filter';

  @override
  String get dateRangeOptional => '(optional)';

  @override
  String get startDate => 'Start Date';

  @override
  String get endDate => 'End Date';

  @override
  String get clear => 'Clear';

  @override
  String get dateRangeRequiresMembership =>
      'Requires Standard Membership or higher';

  @override
  String selectUpToCount(Object current, Object max) {
    return 'Select up to $max. Current: $current';
  }

  @override
  String get clearSelections => 'Clear Selections';

  @override
  String analyzeRandomMetrics(Object count) {
    return 'Analyze $count random metrics';
  }

  @override
  String get saveSelections => 'Save Selections';

  @override
  String get loadSelections => 'Load Selections';

  @override
  String get saveMetricListName => 'Save Metric List';

  @override
  String get enterListName => 'Enter a name for this metric list:';

  @override
  String get chooseSavedMetrics => 'Choose saved metrics list:';

  @override
  String get noSavedLists => 'No saved metric lists to load at this time.';

  @override
  String get metricListSaved => 'Metric list saved successfully.';

  @override
  String get metricListLoaded => 'Metric list loaded successfully.';

  @override
  String get filters => 'Filters';

  @override
  String get sortBy => 'Sort by:';

  @override
  String get recent => 'Recent';

  @override
  String get name => 'Name';

  @override
  String get count => 'Count';

  @override
  String get namedOnly => 'Named only';

  @override
  String get minMessages => 'Min messages:';

  @override
  String get minimumMessages => 'Minimum messages:';

  @override
  String get executiveSummary => 'Executive Summary';

  @override
  String get metricScores => 'Metric Scores';

  @override
  String get contextualEvidenceExamples => 'Contextual Evidence Examples';

  @override
  String get neutralSynthesis => 'Neutral Synthesis';

  @override
  String analysisOfSender(Object sender) {
    return 'Analysis of $sender (Sender)';
  }

  @override
  String analysisOfReceiver(Object receiver) {
    return 'Analysis of $receiver (Receiver)';
  }

  @override
  String get finalConclusion => 'Final Conclusion';

  @override
  String get metric_1_name => 'Contempt';

  @override
  String get metric_1_description =>
      'Looks for superiority, disgust, mockery, eye-rolling language, or insults that place one partner beneath the other.';

  @override
  String get metric_2_name => 'Defensiveness';

  @override
  String get metric_2_description =>
      'Tracks reflexive self-protection, counterattacks, excuses, and refusal to consider the other person\'s complaint.';

  @override
  String get metric_3_name => 'Stonewalling';

  @override
  String get metric_3_description =>
      'Identifies shutdown, withdrawal, ignoring, refusal to answer, or ending conversations to avoid engagement.';

  @override
  String get metric_4_name => 'Criticism';

  @override
  String get metric_4_description =>
      'Detects attacks on character or personality instead of specific behaviors, needs, or incidents.';

  @override
  String get metric_5_name => 'Gaslighting Indicators';

  @override
  String get metric_5_description =>
      'Flags attempts to make someone doubt memory, perception, sanity, or the legitimacy of their experience.';

  @override
  String get metric_6_name => 'Blame Shifting';

  @override
  String get metric_6_description =>
      'Measures whether responsibility is redirected onto the other partner instead of being acknowledged directly.';

  @override
  String get metric_7_name => 'Escalation Pattern';

  @override
  String get metric_7_description =>
      'Evaluates whether tone, accusations, intensity, or threats increase instead of moving toward resolution.';

  @override
  String get metric_8_name => 'Repair Attempt Recognition';

  @override
  String get metric_8_description =>
      'Checks whether apologies, humor, pauses, reassurance, or peace offerings are noticed and accepted.';

  @override
  String get metric_9_name => 'Accountability Language';

  @override
  String get metric_9_description =>
      'Looks for clear ownership of harm, specific responsibility, and willingness to change behavior.';

  @override
  String get metric_10_name => 'Boundary Respect';

  @override
  String get metric_10_description =>
      'Assesses whether stated limits around time, privacy, body, emotions, or contact are honored.';

  @override
  String get metric_11_name => 'Coercive Control Indicators';

  @override
  String get metric_11_description =>
      'Flags patterns of intimidation, restriction, monitoring, dependency, or control over choices and movement.';

  @override
  String get metric_12_name => 'Threat Language';

  @override
  String get metric_12_description =>
      'Identifies explicit or implied threats involving safety, abandonment, exposure, retaliation, or punishment.';

  @override
  String get metric_13_name => 'Dismissiveness';

  @override
  String get metric_13_description =>
      'Detects brushing off concerns, treating needs as unimportant, or refusing to take distress seriously.';

  @override
  String get metric_14_name => 'Invalidation';

  @override
  String get metric_14_description =>
      'Measures denial, ridicule, or correction of another person\'s emotions instead of acknowledging them.';

  @override
  String get metric_15_name => 'Empathy Expression';

  @override
  String get metric_15_description =>
      'Looks for perspective-taking, care, emotional recognition, and concern for the other person\'s experience.';

  @override
  String get metric_16_name => 'Reciprocity';

  @override
  String get metric_16_description =>
      'Assesses whether attention, effort, apology, compromise, and emotional support flow both ways.';

  @override
  String get metric_17_name => 'Emotional Regulation';

  @override
  String get metric_17_description =>
      'Evaluates ability to stay grounded, pause, self-soothe, and communicate without explosive reactivity.';

  @override
  String get metric_18_name => 'Sarcasm Used as Harm';

  @override
  String get metric_18_description =>
      'Flags sarcasm used to belittle, punish, humiliate, or disguise hostility as humor.';

  @override
  String get metric_19_name => 'Name Calling';

  @override
  String get metric_19_description =>
      'Identifies derogatory labels, insults, profanity directed at the person, or identity-based attacks.';

  @override
  String get metric_20_name => 'Silent Treatment Pattern';

  @override
  String get metric_20_description =>
      'Tracks silence used as punishment, control, avoidance, or withdrawal of connection.';

  @override
  String get metric_21_name => 'Jealousy Framing';

  @override
  String get metric_21_description =>
      'Evaluates suspicion, possessiveness, accusations, or jealousy presented as proof of care.';

  @override
  String get metric_22_name => 'Isolation Pressure';

  @override
  String get metric_22_description =>
      'Flags efforts to separate a partner from friends, family, support systems, or outside perspectives.';

  @override
  String get metric_23_name => 'Financial Control Indicators';

  @override
  String get metric_23_description =>
      'Looks for control of money, spending, employment, access to accounts, or financial independence.';

  @override
  String get metric_24_name => 'Privacy Invasion Indicators';

  @override
  String get metric_24_description =>
      'Detects snooping, password demands, device checks, location tracking, or privacy violations.';

  @override
  String get metric_25_name => 'Apology Specificity';

  @override
  String get metric_25_description =>
      'Measures whether apologies name the exact harm, impact, and future correction instead of staying vague.';

  @override
  String get metric_26_name => 'Forgiveness Pressure';

  @override
  String get metric_26_description =>
      'Flags demands to move on, forgive quickly, or stop discussing harm before repair occurs.';

  @override
  String get metric_27_name => 'Minimization';

  @override
  String get metric_27_description =>
      'Detects downplaying harm, calling serious concerns dramatic, or reducing impact to avoid responsibility.';

  @override
  String get metric_28_name => 'Projection';

  @override
  String get metric_28_description =>
      'Looks for accusations that mirror the speaker\'s own behavior, motives, or unresolved feelings.';

  @override
  String get metric_29_name => 'Interruption Pattern';

  @override
  String get metric_29_description =>
      'Tracks cutting off, talking over, refusing completion, or controlling conversational turns.';

  @override
  String get metric_30_name => 'Topic Deflection';

  @override
  String get metric_30_description =>
      'Identifies changing the subject, bringing up unrelated issues, or avoiding the central concern.';

  @override
  String get metric_31_name => 'Resolution Orientation';

  @override
  String get metric_31_description =>
      'Measures whether messages aim toward solutions, clarity, agreements, and next steps.';

  @override
  String get metric_32_name => 'Mutual Problem Solving';

  @override
  String get metric_32_description =>
      'Assesses collaborative language, shared responsibility, brainstorming, and willingness to find workable compromises.';

  @override
  String get metric_33_name => 'Emotional Flooding';

  @override
  String get metric_33_description =>
      'Detects overwhelm, panic, shutdown, spiraling, or inability to process during conflict.';

  @override
  String get metric_34_name => 'Fear Response Cues';

  @override
  String get metric_34_description =>
      'Looks for appeasing, careful wording, dread, safety concerns, or fear of the partner\'s reaction.';

  @override
  String get metric_35_name => 'Consistency of Claims';

  @override
  String get metric_35_description =>
      'Evaluates whether accounts remain internally consistent across messages and time.';

  @override
  String get metric_36_name => 'Evidence-Based Recollection';

  @override
  String get metric_36_description =>
      'Checks whether claims reference concrete events, quotes, timelines, or observable behavior.';

  @override
  String get metric_37_name => 'Demand Withdrawal Pattern';

  @override
  String get metric_37_description =>
      'Tracks one partner pursuing answers or change while the other avoids, shuts down, or exits.';

  @override
  String get metric_38_name => 'Power Imbalance Indicators';

  @override
  String get metric_38_description =>
      'Flags unequal decision power, fear of consequences, dependence, intimidation, or unilateral control.';

  @override
  String get metric_39_name => 'Respectful Disagreement';

  @override
  String get metric_39_description =>
      'Measures whether conflict preserves dignity, curiosity, and disagreement without degradation.';

  @override
  String get metric_40_name => 'Rupture and Repair Cycle';

  @override
  String get metric_40_description =>
      'Assesses whether conflict is followed by acknowledgment, reconnection, and actual repair.';

  @override
  String get metric_41_name => 'Affection Withdrawal';

  @override
  String get metric_41_description =>
      'Detects love, warmth, sex, attention, or reassurance being withheld as punishment or leverage.';

  @override
  String get metric_42_name => 'Public Humiliation References';

  @override
  String get metric_42_description =>
      'Flags threats, jokes, or actions that embarrass the partner in front of others.';

  @override
  String get metric_43_name => 'Substance-Linked Conflict Cues';

  @override
  String get metric_43_description =>
      'Looks for alcohol or drug use being tied to aggression, unreliability, conflict, or harm.';

  @override
  String get metric_44_name => 'Parenting Conflict Pressure';

  @override
  String get metric_44_description =>
      'Identifies children, custody, parenting roles, or parental guilt used in conflict or leverage.';

  @override
  String get metric_45_name => 'Sexual Boundary Respect';

  @override
  String get metric_45_description =>
      'Assesses respect for consent, pressure, refusal, comfort, timing, and sexual autonomy.';

  @override
  String get metric_46_name => 'Digital Harassment Indicators';

  @override
  String get metric_46_description =>
      'Tracks repeated unwanted messages, spam calls, online pressure, surveillance, or platform-based intimidation.';

  @override
  String get metric_47_name => 'Monitoring or Surveillance Language';

  @override
  String get metric_47_description =>
      'Flags checking whereabouts, demanding proof, tracking behavior, or constant verification.';

  @override
  String get metric_48_name => 'Future Orientation';

  @override
  String get metric_48_description =>
      'Measures whether partners discuss future improvement, commitments, plans, or constructive direction.';

  @override
  String get metric_49_name => 'Safety Planning Signals';

  @override
  String get metric_49_description =>
      'Looks for attempts to seek help, create distance, document harm, or plan for physical/emotional safety.';

  @override
  String get metric_50_name => 'Mutual De-escalation Attempts';

  @override
  String get metric_50_description =>
      'Tracks pauses, calming language, softer tone, timeouts, and attempts by both partners to reduce intensity.';

  @override
  String get metric_51_name => 'Secure Attachment Cues';

  @override
  String get metric_51_description =>
      'Identifies trust, direct reassurance, emotional availability, and comfort with closeness and independence.';

  @override
  String get metric_52_name => 'Anxious Attachment Activation';

  @override
  String get metric_52_description =>
      'Flags protest behavior, urgent reassurance needs, abandonment fear, and heightened sensitivity to distance.';

  @override
  String get metric_53_name => 'Avoidant Attachment Distancing';

  @override
  String get metric_53_description =>
      'Detects emotional minimization, independence defenses, withdrawal from vulnerability, or discomfort with needs.';

  @override
  String get metric_54_name => 'Disorganized Attachment Signals';

  @override
  String get metric_54_description =>
      'Looks for approach-avoid cycles, fear mixed with need, chaotic reactions, or confusing intimacy patterns.';

  @override
  String get metric_55_name => 'Emotional Bids and Responses';

  @override
  String get metric_55_description =>
      'Measures invitations for attention, comfort, or connection and whether they are accepted or missed.';

  @override
  String get metric_56_name => 'Turning Away from Connection';

  @override
  String get metric_56_description =>
      'Flags ignoring, dismissing, or failing to respond to bids for closeness or support.';

  @override
  String get metric_57_name => 'Turning Against Connection';

  @override
  String get metric_57_description =>
      'Detects hostile or punishing responses to attempts at affection, vulnerability, or repair.';

  @override
  String get metric_58_name => 'Positive Sentiment Override';

  @override
  String get metric_58_description =>
      'Looks for generosity, benefit-of-the-doubt, fondness, and interpreting conflict through care.';

  @override
  String get metric_59_name => 'Negative Sentiment Override';

  @override
  String get metric_59_description =>
      'Flags assuming bad intent, interpreting neutral messages negatively, and persistent hostile framing.';

  @override
  String get metric_60_name => 'Harsh Startup Pattern';

  @override
  String get metric_60_description =>
      'Identifies conversations that begin with accusation, attack, contempt, or blame rather than a request.';

  @override
  String get metric_61_name => 'Soft Startup Pattern';

  @override
  String get metric_61_description =>
      'Looks for gentle openings using feelings, needs, specific requests, and non-accusatory language.';

  @override
  String get metric_62_name => 'Physiological Self-Soothing';

  @override
  String get metric_62_description =>
      'Assesses attempts to pause, breathe, take space, or regulate the body before continuing conflict.';

  @override
  String get metric_63_name => 'Conflict Avoidance Pattern';

  @override
  String get metric_63_description =>
      'Tracks repeated avoidance of necessary topics, discomfort, disagreement, or emotional honesty.';

  @override
  String get metric_64_name => 'Volatile Conflict Style';

  @override
  String get metric_64_description =>
      'Detects high-intensity conflict with direct expression that may still include engagement and repair.';

  @override
  String get metric_65_name => 'Validating Conflict Style';

  @override
  String get metric_65_description =>
      'Measures whether partners acknowledge each other\'s perspective while disagreeing.';

  @override
  String get metric_66_name => 'Hostile Conflict Style';

  @override
  String get metric_66_description =>
      'Flags frequent criticism, contempt, defensiveness, attacks, and adversarial framing.';

  @override
  String get metric_67_name => 'Hostile-Detached Pattern';

  @override
  String get metric_67_description =>
      'Identifies cold hostility, emotional disengagement, contempt, and low repair motivation.';

  @override
  String get metric_68_name => 'Compromise Willingness';

  @override
  String get metric_68_description =>
      'Looks for flexibility, negotiation, middle-ground proposals, and sacrifices that respect both needs.';

  @override
  String get metric_69_name => 'Influence Acceptance';

  @override
  String get metric_69_description =>
      'Measures openness to being affected by the partner\'s feelings, needs, or perspective.';

  @override
  String get metric_70_name => 'Gridlocked Conflict Signals';

  @override
  String get metric_70_description =>
      'Flags repeated unsolved issues tied to values, dreams, identity, or chronic incompatibility.';

  @override
  String get metric_71_name => 'Solvable Problem Framing';

  @override
  String get metric_71_description =>
      'Detects practical, concrete problem definitions that can lead to specific agreements.';

  @override
  String get metric_72_name => 'Shared Meaning References';

  @override
  String get metric_72_description =>
      'Looks for values, rituals, goals, memories, or identity language that creates a shared relationship story.';

  @override
  String get metric_73_name => 'Love Map Awareness';

  @override
  String get metric_73_description =>
      'Assesses knowledge of the partner\'s inner world, stressors, preferences, fears, and daily life.';

  @override
  String get metric_74_name => 'Fondness and Admiration';

  @override
  String get metric_74_description =>
      'Identifies appreciation, respect, warmth, compliments, gratitude, and positive regard.';

  @override
  String get metric_75_name => 'Emotional Labor Imbalance';

  @override
  String get metric_75_description =>
      'Flags one partner carrying disproportionate planning, soothing, remembering, explaining, or relationship maintenance.';

  @override
  String get metric_76_name => 'Mental Load Dismissal';

  @override
  String get metric_76_description =>
      'Detects minimizing invisible planning work, household coordination, scheduling, or responsibility tracking.';

  @override
  String get metric_77_name => 'Weaponized Incompetence Cues';

  @override
  String get metric_77_description =>
      'Looks for claiming inability, confusion, or helplessness to avoid fair responsibility.';

  @override
  String get metric_78_name => 'Trauma Trigger Sensitivity';

  @override
  String get metric_78_description =>
      'Measures awareness of triggers, trauma responses, and careful handling of vulnerable topics.';

  @override
  String get metric_79_name => 'Hypervigilance Cues';

  @override
  String get metric_79_description =>
      'Flags scanning for danger, over-monitoring tone, fear of mistakes, or constant emotional alertness.';

  @override
  String get metric_80_name => 'Abandonment Fear Language';

  @override
  String get metric_80_description =>
      'Detects fear of being left, replaced, ignored, discarded, or emotionally deserted.';

  @override
  String get metric_81_name => 'Reassurance Seeking Pattern';

  @override
  String get metric_81_description =>
      'Tracks repeated requests for proof of love, commitment, safety, or continued interest.';

  @override
  String get metric_82_name => 'Pursuer-Distancer Cycle';

  @override
  String get metric_82_description =>
      'Identifies one partner escalating pursuit for closeness while the other increases distance.';

  @override
  String get metric_83_name => 'Resentment Accumulation';

  @override
  String get metric_83_description =>
      'Looks for stored grievances, repeated past references, bitterness, and unresolved emotional debt.';

  @override
  String get metric_84_name => 'Scorekeeping Behavior';

  @override
  String get metric_84_description =>
      'Flags transactional counting of faults, favors, sacrifices, or mistakes to gain leverage.';

  @override
  String get metric_85_name => 'Conditional Affection';

  @override
  String get metric_85_description =>
      'Detects love, approval, access, or warmth offered only when compliance is achieved.';

  @override
  String get metric_86_name => 'Love Bombing Indicators';

  @override
  String get metric_86_description =>
      'Flags intense affection, promises, pressure, or idealization used to accelerate attachment or control.';

  @override
  String get metric_87_name => 'Hoovering Attempts';

  @override
  String get metric_87_description =>
      'Identifies attempts to pull someone back through guilt, nostalgia, promises, crises, or sudden affection.';

  @override
  String get metric_88_name => 'DARVO Pattern';

  @override
  String get metric_88_description =>
      'Detects deny, attack, and reverse-victim-offender responses when confronted about harm.';

  @override
  String get metric_89_name => 'Victim Stance Pattern';

  @override
  String get metric_89_description =>
      'Flags recurring self-victimization that avoids accountability or redirects attention from harm caused.';

  @override
  String get metric_90_name => 'Moral Superiority Framing';

  @override
  String get metric_90_description =>
      'Looks for righteousness, purity claims, or ethical superiority used to dominate conflict.';

  @override
  String get metric_91_name => 'Character Assassination';

  @override
  String get metric_91_description =>
      'Detects broad attacks on identity, integrity, mental health, or worth rather than specific behavior.';

  @override
  String get metric_92_name => 'Triangulation Indicators';

  @override
  String get metric_92_description =>
      'Flags bringing third parties into conflict to pressure, compare, validate, or destabilize the partner.';

  @override
  String get metric_93_name => 'Social Comparison Pressure';

  @override
  String get metric_93_description =>
      'Looks for comparisons to exes, friends, other couples, or ideals used to shame or coerce.';

  @override
  String get metric_94_name => 'Autonomy Support';

  @override
  String get metric_94_description =>
      'Measures respect for independent choices, friendships, goals, boundaries, and personal agency.';

  @override
  String get metric_95_name => 'Consent and Choice Respect';

  @override
  String get metric_95_description =>
      'Assesses whether decisions are freely made without pressure, guilt, threats, or manipulation.';

  @override
  String get metric_96_name => 'Collaborative Planning';

  @override
  String get metric_96_description =>
      'Looks for shared scheduling, joint decisions, coordinated responsibilities, and practical follow-through.';

  @override
  String get metric_97_name => 'Repair Follow-Through';

  @override
  String get metric_97_description =>
      'Measures whether promised changes are later reflected in behavior, not just words.';

  @override
  String get metric_98_name => 'Changed Behavior Evidence';

  @override
  String get metric_98_description =>
      'Checks for observable, repeated actions showing learning, adjustment, or reduced harmful behavior.';

  @override
  String get metric_99_name => 'Emotional Safety Language';

  @override
  String get metric_99_description =>
      'Identifies language that invites honesty, lowers fear, protects dignity, and reassures safe expression.';

  @override
  String get metric_100_name => 'Relationship Ambivalence';

  @override
  String get metric_100_description =>
      'Detects uncertainty, mixed commitment, push-pull messaging, or unclear desire to continue.';

  @override
  String get unableToOpenConversations => 'Unable to Open Conversations';

  @override
  String get unableToOpenConversationsBody =>
      'Something went wrong loading your conversations. Please try again.';

  @override
  String get unableToLoadConversationsBody =>
      'Unable to load conversations. Please check your permissions and try again.';

  @override
  String get errorLoadingConversationsBody =>
      'Error loading conversations. Please try again.';

  @override
  String get smsPermissionRequired => 'SMS Permission Required';

  @override
  String get smsPermissionRequiredBody =>
      'To analyze SMS conversations, we need permission to read your messages. Your privacy is important — messages are only analyzed locally and never stored on our servers.';

  @override
  String get grantSmsPermission => 'Grant SMS Permission';

  @override
  String get noSmsConversationsFound => 'No SMS conversations found';

  @override
  String get noConversationsMatchSearch => 'No conversations match your search';

  @override
  String get noSmsMessagesOnDevice =>
      'You don\'t have any SMS messages on this device';

  @override
  String get tryDifferentSearch => 'Try a different search term';

  @override
  String get clearSearch => 'Clear Search';

  @override
  String selectedFile(String filename) {
    return 'Selected: $filename';
  }

  @override
  String get invalidFile => 'Invalid File';

  @override
  String get fileImport => 'File Import';

  @override
  String get fileImportNotImplemented =>
      'File parsing is not yet implemented for this file type.';

  @override
  String get errorPickingFile => 'Unable to open the file. Please try again.';

  @override
  String get readyToCapture => 'Ready to Capture';

  @override
  String get readyToCaptureBody =>
      'Switch to the Messages app now and start taking screenshots.\n\nReturn to this app when you\'re done and tap \"Finish & Process\".';

  @override
  String get gotIt => 'Got it';

  @override
  String get noScreenshotsToProcess => 'No screenshots to process.';

  @override
  String processingScreenshot(int current, int total) {
    return 'Processing screenshot $current of $total...';
  }

  @override
  String get noMessagesFound => 'No Messages Found';

  @override
  String get noMessagesFoundBody =>
      'Could not extract any messages from the screenshots.\n\nPlease ensure the screenshots clearly show the message conversation.';

  @override
  String loadedMessages(int count) {
    return 'Loaded $count messages from screenshots';
  }

  @override
  String get processingError => 'Processing Error';

  @override
  String get processingErrorBody =>
      'Error processing screenshots. Please try again.';

  @override
  String metricListSavedAs(String name) {
    return 'Your selections have been saved as \"$name\".';
  }

  @override
  String metricListLoadedName(String name) {
    return 'Selections \"$name\" have been retrieved and applied.';
  }

  @override
  String conversationLoaded(int count, String name) {
    return 'Loaded $count messages from $name';
  }

  @override
  String get loadButton => 'Load';

  @override
  String get photoPermissionRequired =>
      'Photo library permission is required to detect screenshots.';

  @override
  String get initializingConnection => 'Initializing secure connection...';

  @override
  String get configurationRequired => 'Configuration Required';

  @override
  String get goBack => 'Go Back';

  @override
  String get enableDateRangeFiltering => 'Enable date range filtering';

  @override
  String get clearSelectedDateRange => 'Clear Selected Date Range';

  @override
  String get largeThreadNoticeTitle => 'NOTICE TO USER';

  @override
  String get largeThreadNoticeBody =>
      'When dealing with exceptionally large text threads, some loading screens within this app could exceed over a minute and a half at times.\n\nThe application does not hang. If you see a circling status indicator spinning, the app is still loading.\n\nPlease be patient in those cases, as loading time could be longer than usual compared to your average load time in other applications — especially when dealing with a large dataset such as a thread with 50,000 messages.';

  @override
  String get neverShowThisAgain => 'Never show this message again';

  @override
  String loadingConversationWith(String name) {
    return 'Loading conversation\nwith $name…';
  }

  @override
  String get iosCaptureInstructions =>
      '1. Open the Messages app and select the conversation\n2. Scroll to the oldest message you want to analyze\n3. Tap \"Start Capture\" below\n4. Take screenshots as you scroll through the conversation\n5. When done, tap \"Finish & Process\"';

  @override
  String get howToCaptureIosMessages => 'How to Capture iOS Messages';

  @override
  String get deepSeekApiKey => 'DeepSeek API Key';

  @override
  String get enterYourDeepSeekApiKeyToEnableAiAnalysis =>
      'Enter your DeepSeek API key to enable AI analysis.';

  @override
  String get getYourApiKeyFrom =>
      'Get your API key from: https://platform.deepseek.com';

  @override
  String get apiKey => 'API Key';

  @override
  String get skPlaceholder => 'sk-...';

  @override
  String get yourApiKeyIsStoredSecurely =>
      'Your API key is stored securely on your device and never shared.';

  @override
  String get pleaseEnterApiKey => 'Please enter an API key';

  @override
  String get apiKeySavedSuccessfully => 'API key saved successfully!';

  @override
  String get pleaseBePatientLongerTextThreads =>
      'Please be patient, Longer text thread datasets take quite a while to load';

  @override
  String get almostThereBigOne =>
      'Almost there, Wow this must have been a big one';

  @override
  String get pleaseBePatientLargeDatasets =>
      'Please be patient, large datasets could result in loading times greater than a minute and a half';

  @override
  String continuingToLoadMassiveThread(String name) {
    return 'Continuing to load the massive thread with $name…';
  }

  @override
  String get noMessagesInDateRange =>
      'No messages found in the selected date range. Please select different dates or clear the date filter.';
}
